### ISSUE TITLE
provide a new release that's compatible with puppetlabs/postgresql 8

### ISSUE THREAD

**Issue by bastelfreak** [theforeman/puppet-foreman#1033]
Hi!
could you tag a new release, now that https://github.com/theforeman/puppet-foreman/pull/1031 is merged? That would unblock my CI. Thank you so much!

Cheers, Tim

**Comment by bastelfreak** [comment]
ping @ekohl :) Coul you provide a new release?

**Comment by evgeni** [comment]
I think I managed to do it, as https://forge.puppet.com/modules/theforeman/foreman shows 19.3.0 now ;)
