### ISSUE TITLE
Puppet Environments/Modules are not updated

### ISSUE THREAD

**Issue by rmueck** [theforeman/puppet-foreman#1087]
We have serious problems with importing environments/puppet classes. They are imported only once correctly. But if there are changes in modules, or a module is removed the import does not update this fact. 

Our Environment:
```
RHEL 8.5
foreman-3.3.0-1.el8
foreman-postgresql-3.3.0-1.el8
foreman-proxy-3.3.0-1.el8
rubygem-foreman_puppet-4.0.1-1.fm3_3.el8
puppet-agent-7.18.0-1.el8.x86_64
puppetserver-7.9.0-1.el8
```
The Foreman log is attached (after changed environment and import task)
[production.log](https://github.com/theforeman/puppet-foreman/files/9597253/production.log)

Any help is highly appreciated! Thank you!

**Comment by evgeni** [comment]
Hi,

this is the Puppet module to manage Foreman, not the Foreman plugin to manage Puppet. Tye later can be found at https://github.com/theforeman/foreman_puppet and is the correct place for your issue.

**Comment by ekohl** [comment]
You can also try https://community.theforeman.org/c/support/10

**Comment by rmueck** [comment]
Closed b/c wrong place

**Comment by rmueck** [comment]
Wrong place for this issue
