### ISSUE TITLE
Attempt to use the module standalone causes failure due to implicit dependency on the theforeman/puppet module

### ISSUE THREAD

**Issue by danielkza** [theforeman/puppet-foreman#129]
Hello,

I'm trying to set up The Foreman with an existing Puppet infrastructure. Part of the master bootstrapping is done through puppet itself, so I wanted to have the foreman proxy and reporting configuration done like that as well.

So I installed the theforeman/foreman module first, and tried to include the 'foreman::puppetmaster' class in the master to get things set up automatically, but I get the following error:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: File[/etc/puppet/node.rb] { require => Class[Puppet::Server::Install] }, because Class[Puppet::Server::Install] doesn't seem to be in the catalog
```

which seems to me like theforeman/foreman depends implicitly (but not explicitly in the Modulefile) on theforeman/puppet, but I don't actually want it to manage the whole puppet installation for me, at least for now.

**Comment by ekohl** [comment]
We've improved on this and now document the (optional) dependency in the README. This is in line with the current [puppet style guide](https://docs.puppetlabs.com/guides/style_guide.html#dependencies):
> Soft dependencies should be called out in the README.md, and must not be enforced as a hard requirement in your metadata.json. A soft dependency is a dependency that is only required in a specific set of use cases.

I'm closing this now, but feel free to re-open if you think this should be addressed further.

**Comment by njm506** [comment]
While the update to document the soft dependency is definitely a good move, the original issue still stands - the relationships to '::puppet::server::*' are still present in puppetmaster.pp, and these are only valid if the foreman Puppet module is in use.

There's no functional dependency between the modules, yet it still effectively forces users to define a module with that name, just to make the relationship valid.  I would strongly recommend that you remove these relationships, and instead document that the necessary relationships need to be set up externally, to work with whatever module is being used to configure the puppetmaster (which might not be the Foreman one).

**Comment by ekohl** [comment]
Maybe hide them behind a parameter that defaults to true? Personally I always wanted to move this puppetmaster class to another module and often considered puppet-puppet, but maybe puppet-foreman_proxy would be a better fit. I assume you don't use our puppet-puppet so do you think that would be a good move?

We've also talked about packaging the files and maybe with the upcoming puppet 4 release that might be needed anyway. Then the whole dependencies would move to the package manager and can be solved much cleaner. I now wonder if the notification I just added in #282 should live in puppet-puppet as well, like @domcleal mentioned.

**Comment by njm506** [comment]
A parameter would do the trick, if you wanted to keep the relationships in there.  My personal opinion is that it's the responsibility of the user to set up the appropriate relationships between different modules they're using (unless those modules make functional use of each other).

We're currently using fsalum/puppetmaster for the basic Puppetmaster configuration.  I think it still makes sense for the puppetmaster class to be part of the foreman module, as it's just a remote part of that system, really.  To move it into a different application stack's module seems wrong; if you want to use Foreman, you'll probably already have the module in your repository - it would seem a step backwards to then require another module just to get the ENC / reporting to work.

**Comment by ekohl** [comment]
I suppose we could do ```Class['puppet::server::install'] -> Class['foreman::puppetmaster'] ~> Class['puppet::server::service']``` in puppet-puppet instead of requiring them here. @domcleal what do you think?

**Comment by domcleal** [comment]
@ekohl yep, I think that's fine.

Now I look more closely at puppet::server, [we call foreman::puppetmaster](https://github.com/theforeman/puppet-puppet/blob/82a61d512227c661b64c698a1510f6e541ddc28b/manifests/server/config.pp#L29) from puppet::server::config (which itself is between install & service) so it should just be a case of using anchors.

**Comment by domcleal** [comment]
https://github.com/theforeman/puppet-foreman/issues/300 and https://github.com/theforeman/puppet-puppet/issues/248 should fix this issue, all relationships have moved to theforeman/puppet (which is calling foreman::puppetmaster).
