### ISSUE TITLE
is there a way to set authorize_login_delegation?

### ISSUE THREAD

**Issue by neoice** [theforeman/puppet-foreman#167]
I'm attempting to deploy Foreman in my environment using the `puppet-foreman` module. I would like to be able to set `authorize_login_delegation => true` and I don't see an obvious mechanism for this. is there a settings hash I'm not seeing or is this feature not supported?

**Comment by mmoll** [comment]
This can be done via the foreman_config_entry defined type (not in the settings file but as a change via puppet to the app's internal setting).
