### ISSUE TITLE
decouple from puppetlabs-apache

### ISSUE THREAD

**Issue by neoice** [theforeman/puppet-foreman#168]
(this may actually be two bug reports)

I started with the goal of overriding the resultant apache vhost to enable Kerberos authentication (a few `<Location>` blocks with `mod_auth_kerb` directives). I was unable to extend the apache vhost using `custom_fragment` because it has already been declared. I decided to try and rip out all of the apache management and then manage the apache configs from a completely separate site-local module.

using this Puppet code:

```puppet
    class { 'foreman':
      custom_repo => true,
      passenger   => false,
      ssl         => false,
      use_vhost   => false,
      selinux     => true,
    }
```

results in this error:

    Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: Package[ruby193-rubygem-passenger-native] { before => Class[Apache::Service] }, because Class[Apache::Service] doesn't seem to be in the catalog

I would expect that `passenger => false` would not require `ruby193-rubygem-passenger-native`.

**Comment by mmoll** [comment]
@neoice can this get closed?
