### ISSUE TITLE
WARNING: Cannot consider release theforeman-foreman-2.0. . .   

### ISSUE THREAD

**Issue by rilindo** [theforeman/puppet-foreman#272]
Install theforeman-foreman from puppet returns the following messages:

Notice: Preparing to install into /root/install_foreman/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Warning: Cannot consider release theforeman-foreman-2.0.1: Malformed dependency: puppetlabs/apache. Exception was: Invalid 'version_range' field in metadata.json: Unparsable version range: "~> 0.10"

Warning: Cannot consider release theforeman-tftp-1.4.1: Malformed dependency: puppetlabs/xinetd. Exception was: Invalid 'version_range' field in metadata.json: Unparsable version range: "~> 1.1"

However, it does not appear to be impactful, as the current modules were installed :

/root/install_foreman/modules
â””â”€â”¬ theforeman-foreman (v2.3.1)
  â”œâ”€â”€ adrien-alternatives (v0.3.0)
  â”œâ”€â”€ puppetlabs-apache (v1.2.0)
  â”œâ”€â”¬ puppetlabs-postgresql (v4.1.0)
  â”‚ â”œâ”€â”€ puppetlabs-apt (v1.7.0)
  â”‚ â””â”€â”¬ puppetlabs-concat (v1.1.2)
  â”‚   â””â”€â”€ puppetlabs-stdlib (v4.5.1)
  â”œâ”€â”€ theforeman-concat_native (v1.3.1)
  â””â”€â”¬ theforeman-tftp (v1.4.3)
    â””â”€â”€ puppetlabs-xinetd (v1.3.1)

**Comment by ekohl** [comment]
We've seen the report before, but those are older versions. What version of puppet are you using to download it?

@domcleal I wonder if we should (and can) pull older releases from the forge.

**Comment by rilindo** [comment]
puppet 3.7.3

**Comment by ekohl** [comment]
I hoped it would have been an older version, but alas.

**Comment by domcleal** [comment]
Yeah, I think it's relatively recent behaviour to start mentioning these errors at warning level, presumably while it's depsolving.

I've filed https://tickets.puppetlabs.com/browse/FORGE-238 to try and get them removed.

**Comment by mmoll** [comment]
I'd consider this as an PL problem and close this issue... opinions?

**Comment by domcleal** [comment]
Looks like it's been solved actually, it's been automatically deleted: https://forge.puppetlabs.com/theforeman/tftp/1.4.1/readme
