### ISSUE TITLE
concat requires xinetd puppet module

### ISSUE THREAD

**Issue by logicminds** [theforeman/puppet-foreman#290]
This should be in the fixtures file as xinetd is a dependency of concat.
   
xinetd: 'https://github.com/puppetlabs/puppetlabs-xinetd.git'

**Comment by lazyfrosch** [comment]
puppetlabs-xinetd is required by puppetlabs-tftp, which is used by foreman_proxy, if you decide to use it.

Or have I missed something?

**Comment by domcleal** [comment]
@lazyfrosch theforeman-tftp, but yeah.

I don't get this, how could xinetd be a dep of concat?

**Comment by ekohl** [comment]
I'm also not sure about this. AFAIK puppet-foreman does not need puppetlabs-xinetd nor does concat.

**Comment by lazyfrosch** [comment]
@domcleal whoopsie :D

**Comment by logicminds** [comment]
Looks like I may have spoken too soon.  I was also including smart_proxy into one manifest which brought these dependencies requirement along with it.

```

  include foreman
  include foreman_proxy

```
