### ISSUE TITLE
concat depends on puppet 3.5+

### ISSUE THREAD

**Issue by logicminds** [theforeman/puppet-foreman#291]
I am getting invalid attribute on a file resource because validate_cmd does not exist before puppet 3.5.  We need to bump the puppet dependency requirement and also update the foreman-installer package to 3.7.x

**Comment by mmoll** [comment]
validate_cmd is in puppetlabs-stdlib, which should be compatible with puppet 2.7.20 onwards. Could you provide more details on this, please?

**Comment by logicminds** [comment]
Its not a function so it wouldn't be in stdlib.  Its only in puppet 3.5 and later.  The concat module tries to work around this issue but the catalog fails to compile because of the attribute not being available.  This is probably more of a concat problem than foreman module issue.  Regardless I do think we should require 3.7.x with the puppet installer.  As currently 2.7.x is installed if other other is found.

https://github.com/puppetlabs/puppetlabs-concat/blob/master/manifests/init.pp#L192

Example from concat.
```puppet 
# Only newer versions of puppet 3.x support the validate_cmd parameter
    if $validate_cmd {
      File[$name] {
        validate_cmd => $validate_cmd,
      }
    }
```

**Comment by mmoll** [comment]
could you test if puppetlabs/puppetlabs-concat@a198e5db workd around that?

**Comment by mmoll** [comment]
puppetlabs/puppetlabs-concat#264 is also about this.

**Comment by domcleal** [comment]
If you're running tests, run "rake spec_clean" and then re-run them to download the latest puppet-concat, which has the fix.  If you're using the module, then simply update it or use their latest release.
