### ISSUE TITLE
Installation of foreman-cli fails on CentOS 7

### ISSUE THREAD

**Issue by mattiasgiese** [theforeman/puppet-foreman#327]
I have tried to install foreman-proxy/foreman-cli using the foreman-installer and ran into this issue:

```
[...]
[ INFO 2015-06-03 14:11:54 main]            Requires: ruby193-ruby(abi) = 1.9.1
[ERROR 2015-06-03 14:11:54 main]  Package: ruby193-ruby-wrapper-0.0.2-5.el7.noarch (foreman)
[ INFO 2015-06-03 14:11:54 main]            Requires: ruby193-ruby
[ERROR 2015-06-03 14:11:54 main]  Package: ruby193-rubygem-foreigner-1.7.1-1.el7.noarch (foreman)
[ INFO 2015-06-03 14:11:54 main]            Requires: ruby193-rubygem(activerecord) >= 3.0.0
[ERROR 2015-06-03 14:11:54 main]  Package: foreman-1.8.1-1.el7.noarch (foreman)
[ INFO 2015-06-03 14:11:54 main]            Requires: ruby193-rubygem(json) < 2.0
[ERROR 2015-06-03 14:11:54 main]  Package: ruby193-rubygem-foreigner-1.7.1-1.el7.noarch (foreman)
[ INFO 2015-06-03 14:11:54 main]            Requires: ruby193-rubygems
[ INFO 2015-06-03 14:11:54 main]  You could try using --skip-broken to work around the problem
[ INFO 2015-06-03 14:11:54 main]  You could try running: rpm -Va --nofiles --nodigest
[...]
```

So, it is necessary to enable the ruby193 SCL repository on CentOS 7. 
The following quick hack fixes it:

```
diff --git a/manifests/cli.pp b/manifests/cli.pp
index 54fb998..f22e75e 100644
--- a/manifests/cli.pp
+++ b/manifests/cli.pp
@@ -36,6 +36,13 @@ class foreman::cli (
   validate_string($foreman_url_real, $username_real, $password_real)
   validate_bool($manage_root_config, $refresh_cache)

+  if $::operatingsystem == 'CentOS' and $::operatingsystemmajrelease == '7' {
+    package{'rhscl-ruby193-epel-7-x86_64':
+      ensure => installed,
+      before => Package['foreman-cli'],
+    }
+  }
+
   package { 'foreman-cli':
     ensure => installed,
   } ->
```

It should be discussed wether this hack is viable or if all repositories should be listed as a requirement in the installation manual. I would be glad to help and adjust the manual accordingly.

If the proposed change is sufficient then i will open a pull request.

**Comment by domcleal** [comment]
The configure_scl_repo parameter ought to already do the equivalent, installing foreman-release-scl which depends on the necessary rhscl-* packages: https://github.com/theforeman/puppet-foreman/blob/master/manifests/install/repos/extra.pp#L26

**Comment by ekohl** [comment]
While typing I see @domcleal wrote that I had almost written ....

**Comment by mattiasgiese** [comment]
Here is my foreman-installer answer file for reference: http://pastebin.centos.org/28196/
From my understanding, these extra repos are only activated if foreman is set to be configured?

**Comment by ekohl** [comment]
You're right, I don't think we considered the use case where the cli module is used stand alone but it's a logical thing to do.

**Comment by domcleal** [comment]
foreman::cli also installs `foreman-cli` which depends on Foreman itself, which is why this dependency is needed.

I think I did this as a convenience, since I assumed the class would only ever be used with the rest of the module on the Foreman server, and foreman-cli's a nice abstraction for us so we don't have to worry about what the precise package name is (our SCL RPMs are being renamed at the moment).

**Comment by mmoll** [comment]
Just did a very quick look on it, I think it would be best to scrap the dependency of foreman-cli on foreman. On Debian, this dependency is not there.

**Comment by domcleal** [comment]
Yeah, we could drop the dep, though would also need to change stuff here to install the SCL repos.

**Comment by mmoll** [comment]
I thought hammer was (for now) not dependent on the SCL packages? At least it's not on CentOS 6.

**Comment by domcleal** [comment]
For now, yep.  There's a PR open to change it, so it'll probably change in 1.9/1.0.

**Comment by ekohl** [comment]
What's the status here?

**Comment by mmoll** [comment]
I did have another look at that a few weeks ago and it would probably require massive refactoring.

**Comment by domcleal** [comment]
Correct me if I'm wrong, I think we'd need to:

a) separate repos configuration out of foreman::install, so it can be included from foreman::cli as a dependency
b) remove the Foreman dep on foreman-cli packages

**Comment by ekohl** [comment]
I can't really say that right now, but I think a) sounds like a good thing to do anyway.

**Comment by mmoll** [comment]
Yes, the separation itself is not that much of a problem, but the variable passing with defaults around it looked tedious to me.

**Comment by mmoll** [comment]
mmoll/puppet-foreman@06462c8 is the separation (foreman:repo is not an ideal name, but anyway...), now the question is hot to pass the default parameters...

**Comment by domcleal** [comment]
#404 seems to have broken our nightly tests as the extra SCL repos are getting installed after the foreman::repo now, I think it was probably working by luck before as there's no relationship between foreman::cli and the repos.

Do you have the rest of that ready @mmoll, or shall I take a look?

**Comment by mmoll** [comment]
@domcleal I have nothing in the pipeline, so I'd be grateful if you could handle that

**Comment by domcleal** [comment]
I filed #416 to fix the ordering issue found in tests, but haven't refactored anything to fix this ticket as I'm not quite sure how that should look yet.

**Comment by jyaworski** [comment]
I just ran into this, as another data point.

**Comment by mmoll** [comment]
@ekohl what's the status here, after 7813d88 came in?

**Comment by ekohl** [comment]
Given there is an acceptance test that proves it can be installed without including foreman, I'm going to close this now but if anyone is still running into this please re-open it.
