### ISSUE TITLE
Provide more generic parser functions as separate module

### ISSUE THREAD

**Issue by aptituz** [theforeman/puppet-foreman#335]
Hey guys,

I recently found the two parser functions random_password and cache_data to be incredible useful (in fact so useful, it makes me wonder why puppet doesn't have at least data caching as a core functionality). They could be very well usable in other puppet modules, so I'd like to suggest you to release them as  in a separate puppet module or even separate modules.

Would this be possible?

Best Regards,
Patrick

**Comment by domcleal** [comment]
Yeah, they should probably go to stdlib if possible.

**Comment by aptituz** [comment]
Yes, indeed, if puppetlabs would include them. But an own module would be a good alternative, otherwise.

**Comment by ekohl** [comment]
We did talk about this in the past, but never got around to it. I do wonder how well puppetlabs likes cached_data because it caches on the master, so it doesn't work on multi master setup. One way to find out I suppose :)

**Comment by aptituz** [comment]
Well, not working properly in a multi-master setup is just one use-case. It's still useful in other (and certainly quiet common) use-cases.

**Comment by ekohl** [comment]
I fully agree it's useful.

**Comment by ekohl** [comment]
https://github.com/puppetlabs/puppetlabs-stdlib/pull/521 has been opened, but the initial response isn't positive.

**Comment by ehelms** [comment]
This other option would be to re-purpose and use a puppet-common (we could rename) we have had for a while, e.g. https://github.com/Katello/puppet-common/pull/9

**Comment by ehelms** [comment]
Looks like they rejected that attempt to get the functionality into stdlib but suggested trying extlib. What are your opinions on putting it in extlib vs having our own module that contains common functionalities?

**Comment by aptituz** [comment]
Oh, never heard from extlib before.

Now that I'm aware of it's existence: Might indeed be a better place instead of stdlib. Do you know if it's being maintained in similar diligent way like stdlib?

I don't have a strong opinion weither to put it into your puppet-common module or extlib, but I'd hope it would make it to forge :) (and btw. puppet-common is a quiet over-generic name for a reusable module outside of katello, isn't it? :o)

**Comment by ekohl** [comment]
I could repeat what @aptituz said, but I fully agree.

**Comment by ehelms** [comment]
Based on your feedback, I moved it to extlib -- https://github.com/puppet-community/puppet-extlib/pull/17.  Feedback on the design around namespacing or not would be greatly appreciated.

**Comment by aptituz** [comment]
Great. Will think about it and come back to you ASAP.

**Comment by ekohl** [comment]
```cache_data``` has been pushed but has a different function signature so beware. I think we'll mention this in the changelog once we migrate. ```random_password``` should be done as well IMHO.

**Comment by ehelms** [comment]
My stab at moving random_password to extlib -- https://github.com/puppet-community/puppet-extlib/pull/19 (This one may make sense in stdlib, I just started where I left off)

**Comment by ekohl** [comment]
Given both PRs are merged in extlib, I'm considering this closed. Big thank you to @ehelms for fixing this.

**Comment by aptituz** [comment]
Thank from me aswell!
