### ISSUE TITLE
CentOS 7 with ruby2 support

### ISSUE THREAD

**Issue by PierreR** [theforeman/puppet-foreman#347]
I have got this error trying the module on CentOS 7:

```
Error: Execution of '/bin/yum -d 0 -e 0 -y install foreman-postgresql' returned 1: Error: Package: ruby193-rubygem-rack-jsonp-1.3.1-1.el7.noarch (foreman)
           Requires: ruby193-ruby(abi) = 1.9.1
```

Here is how I use the module:
```
class {'::foreman':
    passenger          => false,
    db_manage          => false,
    configure_scl_repo => false,
    configure_epel_repo => false,
}
```

As a note:

* `scl_repo` should be false by default for CentOS 7 because it does not exist for `7`
* I disable `configure_epel_repo` because it is already setup at that point.

How can I use the native ruby(version 2) that comes with CentOS 7. I do not want to install `1.9.1`. If I am not wrong `foreman` does support `ruby2`.

**Comment by mmoll** [comment]
The ruby193 scl does exist for CentOS and the Foreman packages are built against it as the other variant would be much more complicated as long as CentOS 6 has to be supported.

**Comment by PierreR** [comment]
Then I have go and try to enable the `scl_repo`. It is just surprising because I have heard it was not available for CentOS 7.

**Comment by PierreR** [comment]
Ok the configuration succeeds now (but the service foreman won't start). Anyhow I will investigate the failure and close the issue for now.
Thanks
