### ISSUE TITLE
trusted_puppetmaster_hosts Management

### ISSUE THREAD

**Issue by andreas-weber** [theforeman/puppet-foreman#363]
Where should I add a trusted puppet master? Can't find the right init.pp argument.

**Comment by ekohl** [comment]
Do you mean the one in the [puppet-foreman_proxy project](https://github.com/theforeman/puppet-foreman_proxy), specifically https://github.com/theforeman/puppet-foreman_proxy/blob/f8fa1c48b0a1d8c196e52c530dce5eedd3315121/manifests/init.pp#L61 or really a foreman setting? It looks like we don't have anything for the latter.

**Comment by mmoll** [comment]
`foreman_config_entry` should work for that?
also see #311

**Comment by andreas-weber** [comment]
`foreman_config_entry` did the job. Many thanks to both of you!
