### ISSUE TITLE
[question] more types/providers

### ISSUE THREAD

**Issue by liamjbennett** [theforeman/puppet-foreman#373]
Hi, We have been using this a fork on this module to puppetize our foreman instance for a while now. Our fork contains a large number of types/providers for configuring foreman itself. Is this something you'd like to see contributed back? If so, would you prefer it was small PRs for each type/provider or a one larger one?

https://github.com/opentable/puppet-foreman/tree/master/lib/puppet/type

**Comment by ekohl** [comment]
I think having types/providers for all foreman resources would be a good addition. I'm not sure what the best way to proceed is. Looking at the current types they are all rather minimal in terms of documentation and sometimes have hardcoded defaults. Another difference is that we use our Apipie bindings (see https://github.com/theforeman/puppet-foreman/blob/master/lib/puppet/provider/foreman_smartproxy/rest_v2.rb) which would also be preferred.

Maybe we should first work on one type, see what the exact changes need to be and then repeat it for all other types?

**Comment by liamjbennett** [comment]
Ok, sure. I'll raise the first PR this week and we can work from there. I'll keep this issue open to keep track of the PRs.

**Comment by ekohl** [comment]
Awesome!

**Comment by ekohl** [comment]
@liamjbennett any luck so far? need help?

**Comment by alexjfisher** [comment]
+1 for types for configuring foreman.  In particular, I'd be interested in a type to configure foreman `roles`.  It'd be nice to have those in change control and managed by puppet.

**Comment by mdwheele** [comment]
Is there still interest in this being contributed? I have some dedicated time at work to spend on it and can contribute if there's someone available for reviews / direction.

**Comment by ekohl** [comment]
@mdwheele I think there is. Personally I'm not that familiar with types and providers but I'll be happy to do some reviews/testing.

**Comment by mmoll** [comment]
Closing, as we answered the question, but noting that there was no respective PR.
