### ISSUE TITLE
Smartproxy provider broken under AIO and puppet 4

### ISSUE THREAD

**Issue by GregSutcliffe** [theforeman/puppet-foreman#391]
I think this is already known, but I don't see it logged, so close this if I missed it.

The smart_proxy provider appears to be broken with Puppet 4, you get "Could not find a suitable provider for foreman_smartproxy". I think this is due to to the Apipie bindings not being available to the AIO Puppet ruby stack.

**Comment by ekohl** [comment]
We should implement a basic provider like in https://github.com/theforeman/puppet-foreman/issues/373 which doesn't need apipie.

**Comment by mmoll** [comment]
done in 51e26e5
