### ISSUE TITLE
Test failing with Ruby 1.8.7

### ISSUE THREAD

**Issue by mmoll** [theforeman/puppet-foreman#396]
Pinning rspec-puppet-facts to 1.3.0 fixes this, the only change for 1.4.x was to pull in mcollective.

**Comment by mmoll** [comment]
thinking about it again, I think it would be OK to pin rspec-puppet-facts to 1.3.0 for Ruby 1.8, but leave it open ended for other Rubyies. Opinions?

**Comment by domcleal** [comment]
Is this regarding the report processor failures?  I'm not sure I see the connection.  e.g.

<pre>
       -"metrics" => {"resources"=>{"changed"=>2, "failed"=>1, "out_of_sync"=>2, "restarted"=>1, "total"=>10}, "events"=>{"failure"=>1, "success"=>1, "total"=>2}, "changes"=>{"total"=>2}, "time"=>{"filebucket"=>7.9e-05, "schedule"=>0.000678, "service"=>0.00463, "config_retrieval"=>0.141527891159058, "package"=>0.189955, "file"=>0.090157}},

       +"metrics" => {"resources"=>{"changed"=>2, "failed"=>1, "out_of_sync"=>2, "restarted"=>1, "total"=>10}, "changes"=>{"total"=>2}, "events"=>{"failure"=>1, "success"=>1, "total"=>2}, "time"=>{"filebucket"=>7.9e-05, "schedule"=>0.000678, "service"=>0.00463, "config_retrieval"=>0.141527891159058, "package"=>0.189955, "file"=>0.090157}},

        "reported_at" => "2013-08-29 11:11:44 UTC",

       -"status" => {"applied"=>0, "failed_restarts"=>0, "skipped"=>0, "pending"=>0, "failed"=>1, "restarted"=>1},

       +"status" => {"applied"=>0, "failed_restarts"=>0, "skipped"=>0, "pending"=>0, "failed"=>2, "restarted"=>2},

       

     # ./spec/unit/foreman_report_processor_spec.rb:43
</pre>

The only danger with pinning that gem at different version is when the fact values change and we have to adapt tests, it'll be much more difficult if it varies per Ruby version too.

**Comment by mmoll** [comment]
Yes, this exact failure. I suspect some mcollective<->interaction, but no idea why this is only happening with Ruby 1.8. I didn't want to pin first, but at the end the OS and Puppet versions we're testing with Ruby1.8 probably won't change in the future (other then e.g. Debian 6 tests will be removed at EOL), so the only real problem would be a breaking change in a rspec-puppet-facts major release, IMHO.

**Comment by domcleal** [comment]
Looks like the mcollective-client gem contains a few monkey patches to core objects, perhaps one of those is affecting it.  Sure, go ahead and pin on 1.8 then.
