### ISSUE TITLE
Wrong admin username and password for sqlite database

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [theforeman/puppet-foreman#406]
If sqlite database is in use, `admin_username` and `admin_password` are not used.

**Comment by domcleal** [comment]
The admin_username/password parameters are used any time the module calls the db:seed rake task, but this does only happen once.  If the database has already been seeded then it wouldn't be executed again, and it also won't change any existing values.

**Comment by mateusz-gozdek-sociomantic** [comment]
Ok then, so it looks like database is not properly seeded while using 'sqlite', because my admin user is missing in sqlite database. I am provisioning foreman with puppet using vagrant. Here is part of my manifest (credentials replaced with foo/bar). Host OS: trusty, Guest OS: trusty.

```
        class { 'foreman':
                foreman_url      => 'server.example.com',
                puppetrun        => true,
                unattended       => true,
                authentication   => true,
                db_type          => 'sqlite',
                admin_username   => 'foo',
                admin_password   => 'bar',
                admin_email      => 'admin@example.com',
                passenger        => false,
                require          => Class['puppet'],
        }
````
And dump from `user` table from `/var/lib/foreman/db/production.sqlite3`
```
sqlite> select * from users;
1|foreman_admin|Anonymous|Admin||t||2|2016-03-04 12:15:03.633165|2016-03-04 12:15:03.633165|||||||foreman_admin|t|
2|foreman_api_admin|API|Admin||t||2|2016-03-04 12:15:03.673909|2016-03-04 12:15:03.673909|||||||foreman_api_admin|t|
3|admin|Admin|User|root@example.com|t||1|2016-03-04 12:15:03.740637|2016-03-04 12:15:03.740637|065f323fc5c67a24f8e55fe217345057c1c19e4f|c60944f22f872afc2a85842c5de3f55a8bd92b1e|||||admin|t|
```

**Comment by domcleal** [comment]
Ah, it might be getting seeded during package installation as our package scripts will also run the migrate/seed tasks as postinstall steps.

**Comment by ekohl** [comment]
Does that mean this is a packaging issue or how can we fix this?

**Comment by domcleal** [comment]
I think either: a) remove the seed step from the default postinst in packages so users or the installer have to run it post-installation, or b) Foreman or packages provide a response file mechanism so the installer can write a file of configuration information prior to installation to use during seeding.

On Debian-based OSes, debconf (via package's responsefile) could potentially be used to provide data or enable/disable seeding entirely during installation, but that's not very portable.

**Comment by ekohl** [comment]
Does seeding post-installation also happens on upgrade and if so, do we break upgrades by removing it?

**Comment by domcleal** [comment]
Yes, and yes.

**Comment by ekohl** [comment]
@mateusz-gozdek-sociomantic it looks like you're using the module directly rather than through the installer. Is that correct?

In the installer context we could detect an already seeded database and warn. In the direct module use case I feel like a foreman_user type that ensures a user with a password would be a better fit than (ab)using seeding for it.

**Comment by mateusz-gozdek-sociomantic** [comment]
Yes. it was the direct usage of the module. Using foreman_user sounds good, however in my opinion, if there is a parameter `admin_username` and `admin_password`, I would expect it to ensure that those credentials exists and are correct.

**Comment by ekohl** [comment]
I agree they're a bit misnamed and imply to do more than they actually do.

**Comment by mateusz-gozdek-sociomantic** [comment]
Then maybe they should be renamed to something like `seed_admin_username` or even `postgresql_seed_admin_username` to exactly describe it's role. In my opinion, changing the description in parameter documentation would be a good start.

**Comment by ekohl** [comment]
@mmoll given we're closing in on a release and it's a major version, should we rename these parameters to ```seed_```?

**Comment by mmoll** [comment]
Sorry, that slipped off my radar... 8.0.0 is already released to the forge, but I would be more than willing to accept a PR for the documentation.

**Comment by ekohl** [comment]
With 10.0 coming up (we already merged breaking changes) we should include this. I'm leaning to `initial_x` or `seed_x`.

**Comment by ekohl** [comment]
New major, new chances: 81fcf11a48d3b5bee659e9a84c8927701e5d2674 finally renamed it.

**Comment by mateusz-gozdek-sociomantic** [comment]
Yay :tada:
