### ISSUE TITLE
[question] APT repo handling

### ISSUE THREAD

**Issue by lazyfrosch** [theforeman/puppet-foreman#428]
Is there a reason for us not using puppetlabs-apt in the module here?

I noticed it while APT notified me about an unknown key.

We should use ::apt there, and add the key id of the current key.

Whats your opinion? I could do a PR...

**Comment by domcleal** [comment]
I can't think of a reason, I don't see why it couldn't be refactored.

**Comment by mmoll** [comment]
:+1: for using pl-apt also here.

**Comment by lazyfrosch** [comment]
How about updating pl-apt to 2.2.x ?

**Comment by domcleal** [comment]
The metadata permits 2.2.x already, so probably fine to update the minimum version too if that's required.

**Comment by lazyfrosch** [comment]
Please continue discussion in #429
