### ISSUE TITLE
Remove foreman::plugin::ovirt_provision

### ISSUE THREAD

**Issue by domcleal** [theforeman/puppet-foreman#443]
Per https://github.com/theforeman/foreman-packaging/commit/60ca1687bc1588f547cfe722d4bbd99b0cf90d78, the package is removed from 1.12. In the first release that doesn't support 1.11, the class can be removed too.

**Comment by ekohl** [comment]
:+1:

**Comment by mmoll** [comment]
I gues this can get closed now? :)
