### ISSUE TITLE
Support for AIO Puppet foreman.yaml settings file

### ISSUE THREAD

**Issue by dLobatog** [theforeman/puppet-foreman#451]
AIO puppet config dir is configured by default on ~/.puppetlabs/etc/puppet/  

However, the location of the YAML file node.rb uses is not configurable, and defaults to the regular Puppet dir (/etc/puppet). I think this should be an option on the installer or it should look in both places if one doesn't contain what's expected.

https://github.com/theforeman/puppet-foreman/blob/master/files/external_node_v2.rb#L14

**Comment by domcleal** [comment]
> AIO puppet config dir is configured by default on ~/.puppetlabs/etc/puppet/

You're running the Puppet Server as a non-standard user I guess?  It'd normally be /etc/puppetlabs/puppet/.

**Comment by mmoll** [comment]
what's the status here?

**Comment by dLobatog** [comment]
I was running AIO as my user, I suppose it's not a high prio issue - not sure if we even want to support it

**Comment by mmoll** [comment]
I guess we don't... ok to close this issue?

**Comment by dLobatog** [comment]
Yeah - can be reopened if someone else complains later
