### ISSUE TITLE
documentation link broken that supposed to point here

### ISSUE THREAD

**Issue by elcangri2124** [theforeman/puppet-foreman#453]
Helo,

Was not sure where to open this. In the foreman instructions in https://theforeman.org/manuals/1.11/index.html#3.3InstallFromPackages  in the section The full foreman.conf template from the installer is available here for comparison. The link mentioned in there is broken.

**Comment by domcleal** [comment]
We don't maintain a full template any more, so I don't have a quick fix for the docs apart from removing it: https://github.com/theforeman/theforeman.org/pull/627.

Thanks for the report.
