### ISSUE TITLE
Add AIO package path knowledge to params.pp

### ISSUE THREAD

**Issue by zipkid** [theforeman/puppet-foreman#457]
only $puppet_ssldir is using the $aio_package variable in params.pp while many other paths differ accordiong to that setting. (This is already implemented in the puppet-puppet module so could mostly be copied from there.)

**Comment by mmoll** [comment]
What problems are you seeing exactly and how do you use this module? The part of the module using these variables is normally only used by puppet-puppet, which passes all the needed parameters: https://github.com/theforeman/puppet-puppet/blob/master/manifests/server/config.pp#L192

**Comment by zipkid** [comment]
You are right, i am mixing my old foreman hiera config with this new version and had a wrong setting.
Correcting that made it work. 
Sorry.
