### ISSUE TITLE
Defining 'custom_repo' as 'true' in Foreman ENC Still Results in Creation of EPEL and SCL Repos on EL 7

### ISSUE THREAD

**Issue by jadamcraig** [theforeman/puppet-foreman#467]
I have attempted to override the 'custom_repo' parameter to 'true' (with Key Type set to 'boolean') from the Foreman ENC.  Based on Foreman's YAML output, I can see that this is getting distributed to the nodes:

```
foreman:
[...]
    custom_repo: true
    puppetrun: true
[...]
```

However, even after deleting the '/etc/yum.repos.d/epel.repo' file and running Puppet again, I see that the repository is being re-added by the module.

```
 ⚡ root@puppet.dev  ~  puppet agent -t                  
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for <redacted>
Info: Applying configuration version '1469189976'
Notice: /Stage[main]/Foreman::Repos::Extra/Yumrepo[epel]/ensure: created
Info: changing mode of /etc/yum.repos.d/epel.repo from 600 to 644
Notice: Applied catalog in 5.69 seconds
```

The module does appear to respond as expected when manipulating the 'puppetrun' parameter within the Foreman ENC using the 'boolean' Key Type.

We have a local copy of EPEL stashed on a local mirror which we'd prefer instead, making it critical that enabling the 'custom_repo' parameter on this module be effective.

If I am missing something, please let me know!

**Comment by jadamcraig** [comment]
I should also clarify that I am currently running the latest version of the module from Puppet Forge (ver. 5.2.2).

**Comment by domcleal** [comment]
`$custom_repo` controls only the Foreman repo definitions, change `$configure_epel_repo` for EPEL.

**Comment by jadamcraig** [comment]
Thanks, Dominic!  I've also attempted manipulating the '$configure_epel_repo' parameter using the boolean Key Type within Foreman with the same result -- ie., regardless to whether set to 'true' or 'false', the 'epel.repo' file is still created.

**Comment by domcleal** [comment]
I'd suggest adding some debug then to `foreman::repos::extra` to notify the current value of the parameter.  It's a pretty simple class and parameter and is also tested in spec/classes/foreman_repos_extra_spec.rb so I think it's working correctly.

**Comment by jadamcraig** [comment]
Confirmed.  My mistake!  Thanks!
