### ISSUE TITLE
foreman::rake {'apipie:cache:index'} not scheduled with db_managed=>false

### ISSUE THREAD

**Issue by mgriffin13** [theforeman/puppet-foreman#473]
In my highly available, distributed Foreman installation, we use an externally managed postgresql database, so all of my nodes are set to $db_manage=>false. If this parameter is false, though, then **foreman::rake { 'apipie:cache:index' }** is never scheduled to run, which causes downstream impacts that rely on the cache being present. I dont want foreman-rake to be scheduled every time puppet runs, but I need the cache to be built when Foreman is initially installed.

**Comment by mmoll** [comment]
@domcleal @ekohl a very naive approach, could this work in general?
```diff
--- a/manifests/database.pp
+++ b/manifests/database.pp
@@ -1,9 +1,7 @@
 # Set up the foreman database
 class foreman::database {
-  if $::foreman::db_manage {
     validate_string($::foreman::admin_username, $::foreman::admin_password)
 
-    $db_class = "foreman::database::${::foreman::db_type}"
     $seed_env = {
       'SEED_ADMIN_USER'       => $::foreman::admin_username,
       'SEED_ADMIN_PASSWORD'   => $::foreman::admin_password,
@@ -20,7 +18,12 @@ class foreman::database {
       $foreman_service = Class['foreman::service']
     }
 
-    class { $db_class: } ~>
+  if $::foreman::db_manage {
+    $db_class = "foreman::database::${::foreman::db_type}"
+    class { $db_class:
+      notify => foreman_config_entry['db_pending_migration']
+    }
+  }
     foreman_config_entry { 'db_pending_migration':
       value => false,
       dry   => true,
@@ -38,5 +41,4 @@ class foreman::database {
     foreman::rake { 'apipie:cache:index':
       timeout => 0,
     }
-  }
 }
```

**Comment by domcleal** [comment]
Yeah, it probably would, though I think a new parameter for whether to run db:migrate/seed is necessary as there are still cases (e.g. multi-host) where they should be disabled to avoid multiple systems running the same commands simultaneously.
