### ISSUE TITLE
Parameter name failed on Concat_fragment[Apache ports header]: name is missing group or name.

### ISSUE THREAD

**Issue by jurim76** [theforeman/puppet-foreman#494]
My puppet definition:
  class { 'foreman':
    unattended => false,
    authentication => false,
    db_type => 'mysql',
    db_password => 'foreman',
  }

Error while running "puppet agent -t" on node

Error: Failed to apply catalog: Parameter name failed on Concat_fragment[Apache ports header]: name is missing group or name. Name format must be 'group+fragment_name' at /srv/puppet/env/production/modules/concat/manifests/fragment.pp:55

Debian 8 Jessie
puppet version 3.8.5-2
Installed puppet's modules:
puppetlabs-apache version: "1.10.0"
puppetlabs-concat version: "2.2.0"
theforeman-concat_native" version: "1.5.0"
theforeman-foreman version: "2.2.4"

**Comment by mmoll** [comment]
>  theforeman-foreman version: "2.2.4"

That version is two years old. Please use a recent version of that module, or (if for any reason you must use a version that old) downgrade the dependent modules to versions that were released at that time.

**Comment by mmoll** [comment]
FWIW, I guess the puppetlabs-concat is too new.

**Comment by jurim76** [comment]
Hmm, this is strange. I've installed the module as many others, via puppet

> puppet module --modulepath=./modules  upgrade theforeman-foreman
Notice: Preparing to upgrade 'theforeman-foreman' ...
Notice: Found 'theforeman-foreman' (v2.2.4) in /root/git/puppet/modules ...
Error: Could not upgrade module 'theforeman-foreman' (v2.2.4 -> latest)

**Comment by mmoll** [comment]
> Error: Could not upgrade module 'theforeman-foreman' (v2.2.4 -> latest)

Try --verbose, maybe it'll show what exactly failed in that process.
