### ISSUE TITLE
Class[Mysql::Server::Account_security] is already declared; cannot redeclare 

### ISSUE THREAD

**Issue by jurim76** [theforeman/puppet-foreman#496]
My class definition

  class { 'foreman':
    unattended => false,
    authentication => false,
    db_type => 'mysql',
  }

Error while running "puppet agent -t" on node

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Class[Mysql::Server::Account_security] is already declared; cannot redeclare at /srv/puppet/env/testing/modules/mysql/manifests/server.pp:67 on node

Debian 8 Jessie
puppet version 3.8.5-2
Installed puppet's modules:
puppetlabs-mysql version: 3.9.0
puppetlabs-apache version: 1.10.0
puppetlabs-concat version: 2.2.0
puppet-extlib version: 0.11.3
theforeman-foreman version: 6.0.0

**Comment by domcleal** [comment]
Do you have any mysql::* classes applied to the host? What classes are applied?

**Comment by jurim76** [comment]
I have definitions in hiera/common.yaml

mysql::server::remove_default_accounts: true
mysql::server::root_password:           *****
mysql::server::package_name:           percona-server-server-5.6
mysql::client::package_name:            percona-server-client-5.6

**Comment by domcleal** [comment]
Those are only parameters, do you have _any_ classes applied to the host apart from 'foreman'?

**Comment by jurim76** [comment]
No, just foreman class applied.

**Comment by domcleal** [comment]
> mysql::server::remove_default_accounts: true

This is causing the duplicate declaration, as foreman::database::mysql includes the same mysql::server::account_security class.

You can leave out and Foreman's class will include it, or submit a patch to change the implementation (e.g. set mysql::server::remove_default_accounts in Foreman installer's Hiera config instead of including the class in foreman::database::mysql).
