### ISSUE TITLE
Passenger versions

### ISSUE THREAD

**Issue by rmb938** [theforeman/puppet-foreman#499]
Since the new passenger versions aren't currently supported (See: http://projects.theforeman.org/issues/17093) can this module tell tell apache to not manage the passenger repo (See: https://forge.puppet.com/puppetlabs/apache#class-apachemodpassenger-1) and either install passenger via epel or the foreman yum repos.

**Comment by domcleal** [comment]
Set `apache::mod::passenger::manage_repo: false` via Hiera or disable SELinux.

**Comment by ekohl** [comment]
For the installer we already do set it to false on RH-based systems. For direct use we don't want to manage the passenger module. You can still do so yourself, either through Hiera or in your profile modules.
