### ISSUE TITLE
Wrong foreman::params::etcdir variable on CentOS 7

### ISSUE THREAD

**Issue by dnaeon** [theforeman/puppet-foreman#523]
The `etcdir` variable is wrongly set on CentOS 7 with Puppet 4 AIO.

* https://github.com/theforeman/puppet-foreman/blob/master/manifests/params.pp#L100

It is set to `/etc/puppet`, while with the AIO package for Puppet 4 this should be `/etc/puppetlabs`

A better approach might be to check first whether `$aio_package` is `true` and then set the `etcdir` respectively.

**Comment by mmoll** [comment]
normally that part of the foreman module is used and parametrized by the theforeman-puppet module, which problem do you see specifially?

**Comment by dnaeon** [comment]
Here's what happens if I try to apply the `foreman::puppetmaster` class on my Puppet 4 Server.

```
Info: Using configured environment 'foreman'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for <fqdn>
Info: Applying configuration version '1485874132'
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir - /etc/puppet/foreman.yaml20170131-21987-1eeexep.lock at 31:/etc/puppetlabs/code/environments/foreman/modules/foreman/manifests/puppetmaster.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir - /etc/puppet/foreman.yaml20170131-21987-1eeexep.lock at 31:/etc/puppetlabs/code/environments/foreman/modules/foreman/manifests/puppetmaster.pp
Wrapped exception:
No such file or directory @ dir_s_mkdir - /etc/puppet/foreman.yaml20170131-21987-1eeexep.lock
Error: /Stage[main]/Foreman::Puppetmaster/File[/etc/puppet/foreman.yaml]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir - /etc/puppet/foreman.yaml20170131-21987-1eeexep.lock at 31:/etc/puppetlabs/code/environments/foreman/modules/foreman/manifests/puppetmaster.pp
```

The `etcdir` parameter, which is used in `foreman::puppetmaster` class is with a wrong value, since with Puppet 4 the path is not `/etc/puppet`, but `/etc/puppetlabs` instead.

On a side note the `foreman::puppetmaster` class also deploys the `foreman.rb` reports scripts in the wrong location. Again this is a wrong parameter for the AIO package.

This script here:

* https://github.com/theforeman/puppet-foreman/blob/master/manifests/puppetmaster.pp#L44

Is deployed in the wrong path, because of this here:

* https://github.com/theforeman/puppet-foreman/blob/master/manifests/params.pp#L116

Hope that makes things clearer.

**Comment by mmoll** [comment]
Please see https://github.com/theforeman/puppet-puppet#foreman-integration and the Usage section in that README. `foreman::puppetmaster` is not being testing as used standalone as you're intenting (although it might work, but then you need to paramterize it, as theforeman-puppet does)

**Comment by dnaeon** [comment]
Oh.. there is a `puppet_etcdir` parameter already for `foreman::puppetmaster`, which I've overlooked..

Thanks, will use it.
