### ISSUE TITLE
Add server health check to foreman report script

### ISSUE THREAD

**Issue by peimanja** [theforeman/puppet-foreman#524]
Our infrastructure is in AWS and foreman server is sitting in a standalone setup. We send reports using this module (foreman report script) after each puppet apply. If the foreman server is unreachable (foreman Ec2 instance didn't have other security groups as ingress), we get a long timeout and the timeout in the module has no effects on this. Is it possible to add something like this to the script:

```ruby
SETTINGS = YAML.load_file($settings_file)
server_uri = SETTINGS[:url]
uri = URI.parse(server_uri)
server = Net::HTTP.new(uri.host, uri.port)
server.verify_mode = OpenSSL::SSL::VERIFY_NONE
server.read_timeout = 5
server.open_timeout = 5
server.use_ssl     = uri.scheme == 'https'
resp = server.start() {|server|
server.get("#{uri.path}/status")
}
if resp.code != '200'
   puts resp.code
   abort('something is wrong with the foreman server!')
end
```

**Comment by stbenjam** [comment]
You'd get this in faster by opening a pull request directly with your changes.  The file is here, it probably just needs `open_timeout` set too.

https://github.com/theforeman/puppet-foreman/blob/master/files/foreman-report_v2.rb#L46

**Comment by ekohl** [comment]
Closing for https://github.com/theforeman/puppet-foreman/pull/525
