### ISSUE TITLE
Manifest should support apache::vhost 'access_log_format'

### ISSUE THREAD

**Issue by elconas** [theforeman/puppet-foreman#529]
We are running foreman behind a proxy / load balancer. We want to log the real IP's of clients, therefore we must change the log formal on apache (%a instead of %h). 

However the current version of the module does not allow setting "access_log_format" of apache::vhost. This can easily be added (then we can switch to 'forward' - see https://github.com/puppetlabs/puppetlabs-apache#log_formats).

**Comment by ekohl** [comment]
So the not so pretty workaround is to use ```foreman::config::passenger::fragment``` do include it, but we could expose it on the ```foreman::config::passenger``` class as a parameter. Then you can use hiera to override it. A step further would be to also expose it in the main class, but I'd like to avoid that if possible because we already have a lot of parameters.
