### ISSUE TITLE
Extra messaging when running the foreman_config_entry provider

### ISSUE THREAD

**Issue by cristifalcas** [theforeman/puppet-foreman#538]
We have those messages for every usage of foreman_config_entry. You can notice that the actual value is the same, but because of the extra messaging it tries to updated them every time. I don't know from where those extra messages are comming,

    Notice: /Stage[main]/Foreman::Database/Foreman_config_entry[db_pending_migration]/value: value changed 'Successfully encrypted field for Setting::Auth oauth_consumer_key
    Successfully decrypted field for Setting::Auth oauth_consumer_key
    Successfully decrypted field for Setting::Auth oauth_consumer_key
    Successfully decrypted field for Setting::Auth oauth_consumer_key
    Successfully encrypted field for Setting::Auth oauth_consumer_secret
    Successfully decrypted field for Setting::Auth oauth_consumer_secret
    Successfully decrypted field for Setting::Auth oauth_consumer_secret
    Successfully decrypted field for Setting::Auth oauth_consumer_secret
    false' to 'false'

**Comment by mmoll** [comment]
http://projects.theforeman.org/issues/18200
