### ISSUE TITLE
Redhat/Fedora puppet-agent-oauth' returned 1: Error: Unable to find a match.

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/puppet-foreman#547]
Guys following the https://github.com/theforeman/puppet-foreman/blob/master/manifests/providers/params.pp the packages don't exists (anymore) in CentOS 7.3 and Fedora 25.

Tho in Fedora  rubygems-oauth does exists. and is not applied for the Puppet 4 path.

If I change:

```
  case $::osfamily {
    'RedHat': {
      if $::rubysitedir =~ /\/opt\/puppetlabs\/puppet/ {
#        $oauth_package = 'puppet-agent-oauth'
        $oauth_package = 'rubygem-oauth'
      } else {
        $oauth_package = 'rubygem-oauth'
      }
      $json_package = 'rubygem-json'
      $apipie_bindings_package = 'rubygem-apipie-bindings'
    }

```

I do get a beter run but I do endup with:

`Error: Could not find a suitable provider for foreman_smartproxy`

Does this file needs some update ?

**Comment by ekohl** [comment]
Which puppet version are you using and what are is the yum repo you are using?

**Comment by Yamakasi** [comment]
For puppet ? The puppetlabs pc1.

**Comment by domcleal** [comment]
Then the original manifest (installing `puppet-agent-oauth`) was correct, and the reason you get that error is that you've modified it to install the wrong package.

The `puppet-agent-oauth` package is provided by the Foreman repository for CentOS 7.3: http://yum.theforeman.org/releases/1.14/el7/x86_64/puppet-agent-oauth-0.5.1-3.el7.noarch.rpm. Ensure you have it enabled. Fedora 25 is not supported by Foreman.

**Comment by Yamakasi** [comment]
Yes seen it, thanks for the update!

2017-04-03 12:38 GMT+02:00 Dominic Cleal <notifications@github.com>:

**Comment by Yamakasi** [comment]
I actually changed that package name as I was searching where this went wong, I found the package and tested it out. Now I'm on F24 I see the same result with the above code default.

It seems that the foreman_proxy repo doesn't contain the package and we need the foreman repo for this module as well. Why don't we add it ?

**Comment by domcleal** [comment]
You've filed this again at https://github.com/theforeman/puppet-foreman_proxy/issues/340. See https://github.com/theforeman/puppet-foreman_proxy/issues/340#issuecomment-291135500, not a bug in either module.
