### ISSUE TITLE
Add Passenger repo management

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [theforeman/puppet-foreman#550]
It would be great to be able to disable the installation of the Passenger repo; apache::mod::passenger has support for this, so I don't think it would be too difficult to add a parameter to pass through to that class. If there are no objections, I could submit a PR

**Comment by mmoll** [comment]
This should be done via hiera and foreman-installer does this by default: theforeman/foreman-installer#185

**Comment by 01100010011001010110010101110000** [comment]
You're quite right, thank you.
