### ISSUE TITLE
passenger.repo created even when custom_repo => false

### ISSUE THREAD

**Issue by alexjfisher** [theforeman/puppet-foreman#554]
According to the parameter docs for custom_repo...
> if set to true, no repo will be added by this module

but, since https://github.com/puppetlabs/puppetlabs-apache/commit/9996cb23a118ee14806197a8597be1c0cbe2e70b, apache::mod::passenger creates a passenger yumrepo resource unless `manage_repo` is set to false.

Instead of 'including' apache::mod::passenger [here](https://github.com/theforeman/puppet-foreman/blob/a46d6b36acf021021a2962ce98e084e9606dca99/manifests/config/passenger.pp#L96), should it be declared it with `manage_repo => !$::foreman::custom_repo`?

Probably worth checking to see if it's already been defined to prevent creating duplicate resource issues for users.

**Comment by domcleal** [comment]
See #550 among others.

Declaring the class as a resource may conflict with other modules (e.g. puppet-puppet) and could simply be unreliable unless they also declare the class with the same parameters. Using Puppet lookup/Hiera to set the class parameter is best.

This could be documented in this module too.

**Comment by alexjfisher** [comment]
@domcleal yeah, I thought of just using hiera but thought that was some sort of roles and profiles antipattern. https://docs.puppet.com/pe/2017.1/r_n_p_intro.html#a-summary-of-the-roles-and-profiles-method

> If a component class has parameters, you specify them in the profile; never use Hiera to override component class params.

I had a PR almost ready (that at least did something half way sensible with `if defined`), but nevermind.

**Comment by alexjfisher** [comment]
Ignore me.  I'm being an idiot.  There's obviously nothing to stop me declaring the apache::mod::passenger class in my profile if I don't want to add extra hiera.
