### ISSUE TITLE
Make PassengerMaxPoolSize configurable

### ISSUE THREAD

**Issue by kasimon** [theforeman/puppet-foreman#555]
For servers with small memory (4GB or less), the default maximum number of 6 passenger workers is too high. For these systems, an option to set PassengerMaxPoolSize as already possible with PassengerMinInstances would help a lot.

**Comment by ekohl** [comment]
This should be set on ```apache::mod::passenger```. You can either set this through hiera or be sure to define ```class { '::apache::mod::passenger': passenger_max_pool_size => 4 }``` before including the Foreman module. The parameter is a server global variable according to https://www.phusionpassenger.com/library/config/apache/reference/#passengermaxpoolsize so the apache module is responsible for the setting. Managing that in this module would break other use cases and is not something we should be doing.
