### ISSUE TITLE
foreman::version parameter not fully honored on Debian

### ISSUE THREAD

**Issue by ericy-jana** [theforeman/puppet-foreman#557]
On Debian 8, if I pass a specific version to foreman::version only the foreman::<database_type> package is installed at the specified version.  Other packages are latest.

The code seems to rely on the DB package pulling the others in as dependencies - https://github.com/theforeman/puppet-foreman/blob/7.2.0/manifests/install.pp#L4-L24

But, the dpkg packages themselves don't ensure the dependency packages are the same version (perhaps they do for rpm releases?).  You can see this by, for instance, manually installing foreman-postgresql=1.14.2-1.  foreman-postgresql will indeed be installed as 1.14.2 but we get 1.14.3 for the main foreman package. 

Should the packages should be ensured individually to get the expected versions?

```
# apt-get install -y foreman-postgresql=1.14.2-1 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  foreman foreman-debug foreman-proxy
The following NEW packages will be installed:
  foreman foreman-debug foreman-postgresql foreman-proxy
0 upgraded, 4 newly installed, 0 to remove and 12 not upgraded.
Need to get 0 B/41.5 MB of archives.
After this operation, 160 MB of additional disk space will be used.
Selecting previously unselected package foreman.
(Reading database ... 75465 files and directories currently installed.)
Preparing to unpack .../foreman_1.14.3-1_amd64.deb ...
Unpacking foreman (1.14.3-1) ...
Selecting previously unselected package foreman-debug.
Preparing to unpack .../foreman-debug_1.14.3-1_all.deb ...
Unpacking foreman-debug (1.14.3-1) ...
Selecting previously unselected package foreman-postgresql.
Preparing to unpack .../foreman-postgresql_1.14.2-1_all.deb ...
Unpacking foreman-postgresql (1.14.2-1) ...
Selecting previously unselected package foreman-proxy.
Preparing to unpack .../foreman-proxy_1.14.3-1_all.deb ...
Unpacking foreman-proxy (1.14.3-1) ...
Processing triggers for systemd (215-17+deb8u6) ...
Setting up foreman (1.14.3-1) ...
Setting up foreman-debug (1.14.3-1) ...
Setting up foreman-postgresql (1.14.2-1) ...
Setting up foreman-proxy (1.14.3-1) ...
Processing triggers for systemd (215-17+deb8u6) ...
```

**Comment by domcleal** [comment]
This should be fixed in the packages then so they install a consistent version number. I don't think it's a good idea to workaround it here.

**Comment by domcleal** [comment]
I opened a PR fixing it at https://github.com/theforeman/foreman-packaging/pull/1649.

**Comment by mmoll** [comment]
that got merged and would be cherry-pickable to whatever packaging branches intended
