### ISSUE TITLE
Duplicate declaration: Yumrepo[epel]

### ISSUE THREAD

**Issue by Regner** [theforeman/puppet-foreman#588]
Sorry if there is an obvious fix to this, I am fairly new to Puppet.

I have a `::roles::foreman::server` role that includes my `::profiles::common` profile. Part of my common profile is this module (https://forge.puppet.com/stahnma/epel) which I use by simply `include epel`.

When I run Puppet however I get:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Yumrepo[epel] is already declared in file /etc/puppetlabs/code/environments/production/thirdparty/epel/manifests/init.pp:99; cannot redeclare at /etc/puppetlabs/code/environments/production/thirdparty/foreman/manifests/repos/extra.pp:13 at /etc/puppetlabs/code/environments/production/thirdparty/foreman/manifests/repos/extra.pp:13:5 on node foreman01.local1.example.net
```

As I will need epel on all of my servers I was really hoping to include it in the common profile. Is there a way I can do that and get around this issue?

**Comment by ekohl** [comment]
There is a parameter ```configure_epel_repo``` which can disable management of EPEL. See http://www.puppetmodule.info/modules/theforeman-foreman/puppet_classes/foreman for all parameters.

Please let us know if that solves your issue.

**Comment by Regner** [comment]
That worked to fix the issue. I have a new issue with SSL certs now, but will ask on IRC and open a different issue if needed for that.

Thank you for the quick response.
