### ISSUE TITLE
Wrong mode for node.rb

### ISSUE THREAD

**Issue by mzhaase** [theforeman/puppet-foreman#617]
Line 56 in manifests/puppetmaster.pp should be

mode => '0750'

Otherwise node.rb will not work after the first puppet run with error:

     Exception while executing '/etc/puppetlabs/puppet/node.rb': Cannot run program "/etc/puppetlabs/puppet/node.rb" (in directory "."): error=13, Permission denied

**Comment by ekohl** [comment]
I'm not sure that would actually make a difference. ```0550``` should still give read and execute to the file, just not a write permission. Is there a user issue perhaps where the execution is done by the wrong user/group?

**Comment by mzhaase** [comment]
Interesting, now it actually works. I used mode 0770 so it cannot be group/user dependent. Group and user was always puppet:puppet. It was reproduceable though that it stopped working with 0550 and did work ith 0770. 

Puppetserver 5.1.4
Foreman 1.16

mod 'theforeman-foreman', '8.1.1'
mod 'theforeman-foreman_proxy', '6.0.3'
mod 'theforeman-puppet', '8.1.0'

Since it now actually works I leave it to you whether to close this issue.

**Comment by ekohl** [comment]
I wonder if perhaps it was running under the wrong user or perhaps SELinux? If not then I'm going to close this issue.

**Comment by mzhaase** [comment]
chown was and is puppet:puppet.

SELinux I didn't touch. System was set up with foreman-installer as well.

**Comment by ekohl** [comment]
Thanks for the report anyway. If you do see it again then please report it. We could actually make it world read + executable since nowadays we've split off the settings in a separate file. The 0550 actually comes from when we templated it and included secrets.

**Comment by mzhaase** [comment]
It was actually our deploy job. node.rb did not have the +x flag set in git. In case anyone else stumbles over this issue.
