### ISSUE TITLE
support 1.16 http_proxy config settings

### ISSUE THREAD

**Issue by carazzim0** [theforeman/puppet-foreman#619]
Hi there,

today we upgraded to version 1.16. But I think this module does not support this version yet. I would really like to configure the http_proxy variables introduced in 1.16. (https://www.theforeman.org/manuals/1.16/index.html#5.9HTTP(S)Proxy)

When will 1.16 be supported?

Best regards and thanks
carazzim0

**Comment by ekohl** [comment]
A PR would be highly welcome.

**Comment by mmoll** [comment]
This can/should be rather set in the Foreman appliation config than in the yaml file.

use i.e.
```puppet
    foreman_config_entry { 'http_proxy':
      value => 'https://my.pro.xy:1234',
}
```
