### ISSUE TITLE
Foreman report (No message available)

### ISSUE THREAD

**Issue by kitokirisaki** [theforeman/puppet-foreman#625]
Hello, i changed nothing, but i get the following error in the /var/log/puppetlabs/puppetserver/puppetserver.log file.

```
2018-02-07 12:57:12,629 ERROR [qtp382159318-6183] [puppetserver] Puppet Report processor failed: Could not send report to Foreman at https://{puppethost.tld}/api/config_reports: No message available
["org/jruby/ext/openssl/SSLContext.java:396:in `setup'", "org/jruby/ext/openssl/SSLSocket.java:171:in `initialize'", "/opt/puppetlabs/server/apps/puppetserver/jruby-1_7.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:777:in `connect'", "/opt/puppetlabs/server/apps/puppetserver/jruby-1_7.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:756:in `do_start'", "/opt/puppetlabs/server/apps/puppetserver/jruby-1_7.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:745:in `start'", "/opt/puppetlabs/server/apps/puppetserver/jruby-1_7.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:1293:in `request'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/reports/foreman.rb:69:in `process'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:37:in `process'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:53:in `processors'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:51:in `processors'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:30:in `process'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:14:in `save'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:289:in `save'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:181:in `do_save'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:48:in `call'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:260:in `override'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:47:in `call'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:82:in `process'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:81:in `process'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:87:in `process'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:87:in `process'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:64:in `process'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:62:in `process'", "file:/opt/puppetlabs/server/apps/puppetserver/puppet-server-release.jar!/puppetserver-lib/puppet/server/master.rb:42:in `handleRequest'", "Puppet$$Server$$Master_125555652.gen:13:in `handleRequest'", "request_handler_core.clj:273:in `invoke'", "jruby_request.clj:48:in `invoke'", "jruby_request.clj:33:in `invoke'", "request_handler_service.clj:47:in `handle_request'", "request_handler.clj:3:in `invoke'", "request_handler.clj:3:in `invoke'", "core.clj:2515:in `invoke'", "master_core.clj:729:in `invoke'", "ring.cljc:25:in `invoke'", "ring.cljc:16:in `invoke'", "comidi.clj:245:in `invoke'", "ring_middleware.clj:284:in `invoke'", "core.clj:168:in `invoke'", "core.clj:211:in `invoke'", "core.clj:45:in `invoke'", "core.clj:357:in `invoke'", "core.clj:51:in `invoke'", "ringutils.clj:83:in `invoke'", "http.clj:152:in `invoke'", "http.clj:152:in `invoke'", "http.clj:148:in `invoke'", "legacy_routes_core.clj:180:in `invoke'", "comidi.clj:332:in `invoke'", "legacy_routes_core.clj:114:in `invoke'", "legacy_routes_core.clj:94:in `invoke'", "legacy_routes_core.clj:187:in `invoke'", "legacy_routes_core.clj:153:in `invoke'", "ring.cljc:25:in `invoke'", "ring.cljc:16:in `invoke'", "comidi.clj:245:in `invoke'", "jetty9_core.clj:432:in `invoke'", "normalized_uri_helpers.clj:74:in `invoke'"]
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/reports/foreman.rb:75:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:37:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:53:in `processors'
org/jruby/RubyArray.java:1613:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:51:in `processors'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:30:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:14:in `save'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:289:in `save'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:181:in `do_save'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:48:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:260:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:47:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:82:in `process'
org/jruby/RubyArray.java:1613:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:81:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:87:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:87:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:64:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:62:in `process'
file:/opt/puppetlabs/server/apps/puppetserver/puppet-server-release.jar!/puppetserver-lib/puppet/server/master.rb:42:in `handleRequest'
Puppet$$Server$$Master_125555652.gen:13:in `handleRequest'
```

Now foreman can't receive reports anymore.

if you need any more information i can provide them.

**Comment by ekohl** [comment]
Apologies for the slow reaction. Do you still have this problem? Which versions are you using (Puppet, Foreman, Reporting script)?

**Comment by kitokirisaki** [comment]
Thank you for the reply. The problem started after using a let's encrpt certificate, so i made a rollback. After seeing your message, i tried to reproduce the issue again. So far the issue has not appeared. I'll contact you should the Problem occur again.

**Comment by ekohl** [comment]
Thank you for the update. It could be that we verify the CA cert of foreman to be the puppet one. To use a different CA you need to fix that. So far I haven't done so, but we really need documentation on how to do so.

**Comment by kitokirisaki** [comment]
I used the following documentation https://theforeman.org/2015/11/foreman-ssl.html

**Comment by kitokirisaki** [comment]
@ekohl could you please tell me how to setup the ssl? i think that i broke some parts of the setup again. i only want to replace the forman interface ssl

**Comment by ekohl** [comment]
That blog looks correct except that since Puppet 4 `/etc/puppetlabs/puppet/foreman.yaml` is read if it exists. Otherwise it still falls back to `/etc/puppet/foreman.yaml`. Perhaps you've modified an unused file?

**Comment by kitokirisaki** [comment]
after setting up let's encrypt the same issue appeared again.

/var/log/puppetlabs/puppetserver/puppetserver.log
`2018-03-28 20:03:42,317 ERROR [qtp1504876288-64] [puppetserver] Puppet Report processor failed: Could not send report to Foreman at https://puppet.domain.tld/api/config_reports: No message available
["org/jruby/ext/openssl/SSLContext.java:396:in `setup'", "org/jruby/ext/openssl/SSLSocket.java:171:in `initialize'", "/opt/puppetlabs/server/apps/puppetserver/jruby-1_7.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:777:in `connect'", "/opt/puppetlabs/server/apps/puppetserver/jruby-1_7.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:756:in `do_start'", "/opt/puppetlabs/server/apps/puppetserver/jruby-1_7.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:745:in `start'", "/opt/puppetlabs/server/apps/puppetserver/jruby-1_7.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:1293:in `request'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/reports/foreman.rb:69:in `process'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:37:in `process'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:53:in `processors'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:51:in `processors'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:30:in `process'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:14:in `save'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:289:in `save'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:181:in `do_save'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:48:in `call'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:260:in `override'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:47:in `call'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:82:in `process'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:81:in `process'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:87:in `process'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:87:in `process'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:64:in `process'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:62:in `process'", "file:/opt/puppetlabs/server/apps/puppetserver/puppet-server-release.jar!/puppetserver-lib/puppet/server/master.rb:42:in `handleRequest'", "Puppet$$Server$$Master_239907313.gen:13:in `handleRequest'", "request_handler_core.clj:273:in `invoke'", "jruby_request.clj:48:in `invoke'", "jruby_request.clj:33:in `invoke'", "request_handler_service.clj:47:in `handle_request'", "request_handler.clj:3:in `invoke'", "request_handler.clj:3:in `invoke'", "core.clj:2515:in `invoke'", "master_core.clj:742:in `invoke'", "ring.cljc:25:in `invoke'", "ring.cljc:16:in `invoke'", "comidi.clj:245:in `invoke'", "ring_middleware.clj:284:in `invoke'", "core.clj:168:in `invoke'", "core.clj:211:in `invoke'", "core.clj:45:in `invoke'", "core.clj:357:in `invoke'", "core.clj:51:in `invoke'", "ringutils.clj:83:in `invoke'", "http.clj:152:in `invoke'", "http.clj:152:in `invoke'", "http.clj:148:in `invoke'", "legacy_routes_core.clj:180:in `invoke'", "comidi.clj:332:in `invoke'", "legacy_routes_core.clj:114:in `invoke'", "legacy_routes_core.clj:94:in `invoke'", "legacy_routes_core.clj:187:in `invoke'", "legacy_routes_core.clj:153:in `invoke'", "ring.cljc:25:in `invoke'", "ring.cljc:16:in `invoke'", "comidi.clj:245:in `invoke'", "jetty9_core.clj:433:in `invoke'", "normalized_uri_helpers.clj:74:in `invoke'"]
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/reports/foreman.rb:75:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:37:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:53:in `processors'
org/jruby/RubyArray.java:1613:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:51:in `processors'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:30:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:14:in `save'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:289:in `save'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:181:in `do_save'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:48:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:260:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:47:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:82:in `process'
org/jruby/RubyArray.java:1613:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:81:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:87:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:87:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:64:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:62:in `process'
file:/opt/puppetlabs/server/apps/puppetserver/puppet-server-release.jar!/puppetserver-lib/puppet/server/master.rb:42:in `handleRequest'
Puppet$$Server$$Master_239907313.gen:13:in `handleRequest'
request_handler_core.clj:273:in `invoke'
jruby_request.clj:48:in `invoke'
jruby_request.clj:33:in `invoke'
request_handler_service.clj:47:in `handle_request'
request_handler.clj:3:in `invoke'
request_handler.clj:3:in `invoke'
core.clj:2515:in `invoke'
master_core.clj:742:in `invoke'
ring.cljc:25:in `invoke'
ring.cljc:16:in `invoke'
comidi.clj:245:in `invoke'
ring_middleware.clj:284:in `invoke'
core.clj:168:in `invoke'
core.clj:211:in `invoke'
core.clj:45:in `invoke'
core.clj:357:in `invoke'
core.clj:51:in `invoke'
ringutils.clj:83:in `invoke'
http.clj:152:in `invoke'
http.clj:152:in `invoke'
http.clj:148:in `invoke'
legacy_routes_core.clj:180:in `invoke'
comidi.clj:332:in `invoke'
legacy_routes_core.clj:114:in `invoke'
legacy_routes_core.clj:94:in `invoke'
legacy_routes_core.clj:187:in `invoke'
legacy_routes_core.clj:153:in `invoke'
ring.cljc:25:in `invoke'
ring.cljc:16:in `invoke'
comidi.clj:245:in `invoke'
jetty9_core.clj:433:in `invoke'
normalized_uri_helpers.clj:74:in `invoke'`

OS: debian
RELEASE: 9.4
FOREMAN: 1.16.0
RUBY: ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
PUPPET: 5.5.0

/etc/puppetlabs/puppet/foreman.yaml
`---
:url: "https://puppet.domain.tld"
:ssl_ca: "/etc/letsencrypt/live/puppet.domain.tld/chain.pem" <- changed
:ssl_cert: "/etc/puppetlabs/puppet/ssl/certs/puppet.domain.tld.pem"
:ssl_key: "/etc/puppetlabs/puppet/ssl/private_keys/puppet.domain.tld.pem"
:user: ""
:password: ""
:puppetdir: "/opt/puppetlabs/server/data/puppetserver"
:puppetuser: "puppet"
:facts: true
:timeout: 60
:report_timeout: 60
:threads: null`

/etc/apache2/sites-available/05-foreman-ssl.conf
`  ## SSL directives
  SSLEngine on
#  SSLCertificateFile      "/etc/puppetlabs/puppet/ssl/certs/puppet.domain.tld.pem" <- old
  SSLCertificateFile      "/etc/letsencrypt/live/puppet.domain.tld/cert.pem" <- new
#  SSLCertificateKeyFile   "/etc/puppetlabs/puppet/ssl/private_keys/puppet.domain.tld.pem" <- old
  SSLCertificateKeyFile   "/etc/letsencrypt/live/puppet.domain.tld/privkey.pem" <- new
#  SSLCertificateChainFile "/etc/puppetlabs/puppet/ssl/certs/ca.pem" <- old
  SSLCertificateChainFile "/etc/letsencrypt/live/puppet.domain.tld/chain.pem" <- new
  SSLVerifyClient         optional
  SSLCACertificateFile    "/etc/puppetlabs/puppet/ssl/certs/ca.pem"
  SSLCARevocationFile     "/etc/puppetlabs/puppet/ssl/crl.pem"
  SSLVerifyDepth          3
#  SSLCARevocationCheck    "chain"
#  SSLOptions +StdEnvVars +ExportCertData
  SSLOptions +StdEnvVars
`

**Comment by kitokirisaki** [comment]
@ekohl i dissabled the option `:ssl_ca:` currently in the `/etc/puppetlabs/puppet/foreman.yaml` file. So now it works, but unfortunately without ssl check.

**Comment by dimsua** [comment]
Have some issue when use instruction https://theforeman.org/2015/11/foreman-ssl.html

**Comment by ekohl** [comment]
https://community.theforeman.org/t/replacing-self-signed-certificates/11257/2 is what I used.
