### ISSUE TITLE
$listen_on_interface in foreman::config::passenger doesn't accept interfaces

### ISSUE THREAD

**Issue by bastelfreak** [theforeman/puppet-foreman#649]
hai everybody,

let's assume somebody did something like this in hiera;

```yaml
---
foreman::config::passenger::listen_on_interface: 'etho'
```

from the class description:
https://github.com/theforeman/puppet-foreman/blob/4a1f028aafd787eaafdaa3b3679c9cc2d711ee36/manifests/config/passenger.pp#L7-L8

So I assume an interface name is supposed to be valid. Later on we parse the name like this:

https://github.com/theforeman/puppet-foreman/blob/4a1f028aafd787eaafdaa3b3679c9cc2d711ee36/manifests/config/passenger.pp#L115-L120

And pass it to an `apache::vhost` defined resource:

https://github.com/theforeman/puppet-foreman/blob/4a1f028aafd787eaafdaa3b3679c9cc2d711ee36/manifests/config/passenger.pp#L141-L145

But from the `puppetlabs-apache` module:

https://github.com/puppetlabs/puppetlabs-apache/blob/1ab05064a8e93a0e8bdae73dc673b0a095d1c629/manifests/vhost.pp#L367-L370

$add_listen defaults to true and the foreman module doesn't expose a parameter to disable it. That means that the defined resource expects an IP-Address and not an interface name. Foreman throws this error message:

```
Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Apache::Vhost[foreman]: Mixing IP and non-IP Listen directives is not possible; check the add_listen parameter of the apache::vhost define to disable this (file: /etc/puppetlabs/code/environments/production/modules/apache/manifests/vhost.pp, line: 368, column: 7) (file: /etc/puppetlabs/code/environments/production/modules/foreman/manifests/config/passenger.pp, line: 141)
```

My Puppet code to trigger this, without hiera:

```puppet
class{'foreman':
    db_manage           => true,
    configure_epel_repo => false,
    passenger_interface => $facts['network_primary_interface'],
  }
```

**Comment by bastelfreak** [comment]
okay I did some more debugging. My initial conclusion was horribly wrong here. The puppetlabs-apache module provides a default vhost. it listens on port 80 on all ip addresses / interfaces. Setting `foreman::config::passenger::listen_on_interface: 'etho'` sets the `Listen` directive only for the two foreman vhosts, but not for the default vhost. Since really nobody needs it, we can purge it with this in hiera:

```yaml
---
apache::default_vhost: false
```

and everything is working as expected.

**Comment by ekohl** [comment]
We do indeed set apache::default_vhost to false in our installer (via hiera) but we don't want to manage this in this module so it's left as a users exercise now.

https://github.com/theforeman/puppet-foreman/issues/563 is open to make this more generic so I'm linking it here.
