### ISSUE TITLE
Can't set apache configs other than vhost configs

### ISSUE THREAD

**Issue by thaniri** [theforeman/puppet-foreman#681]
The place where the apache module is included doesn't allow doing apache level configs:

https://github.com/theforeman/puppet-foreman/blob/master/manifests/config/passenger.pp#L103

for instance, using an older version of this module I want to make use of the trace_enable parameter.

Typically this will be done like:

```
class { '::apache':
  trace_enable = $trace_enable,
}
```

However, due to the simple include this doesn't work.

Rewriting the module to actually declare the class like I presented above in the example results in a duplicate class declaration error however.

So the question is, how exactly am I supposed to set apache (NOT vhost) configurations?

**Comment by ekohl** [comment]
There are 2 methods: the first is hiera and the second is defining the apache class before including the foreman (passenger) config:
```puppet
class profiles::foreman {
  class { 'apache':
    trace_enable = $trace_enable,
  }
  include foreman
}
