### ISSUE TITLE
If I specify custom_repo to false on parent class, do not install Yumrepo('passenger') resource from included Apache::Mod::Passenger

### ISSUE THREAD

**Issue by jstewart612** [theforeman/puppet-foreman#684]
In other words, please set the manage_repo param in your call to the same value as custom_repo and presto, your option does what it says it does instead of doing it for all repos EXCEPT passenger.

**Comment by ekohl** [comment]
That's a class we don't manage and can't set. I recommend to use hiera to set `apache::mod::passenger::manage_repo: false` or if you directly use the module to include it in your profile module:
```puppet
class { 'apache::mod::passenger':
  'manage_repo' => false,
}
include foreman
```

**Comment by jstewart612** [comment]
I'd love to, except you do this:

https://github.com/theforeman/puppet-foreman/blob/master/manifests/config/passenger.pp#L105

This results in duplicate resource warnings when I try.

**Comment by ekohl** [comment]
That shouldn't happen if you define the `class { '...': }` before the include. It is compile order dependent. That's why I suggested a profile module. Note that this will not work if you also include the foreman module in your ENC.

**Comment by mmoll** [comment]
what's the status here?
