### ISSUE TITLE
external_node_v2.rb does not import facts with values set to 'false'

### ISSUE THREAD

**Issue by dammsd** [theforeman/puppet-foreman#696]
Current external_node_v2.rb seems to ignore facts where values are set to 'false' (boolean)

I was wondering if this is an intended behaviour

Thanks,

**Comment by ekohl** [comment]
Doesn't that actually happen on the Foreman side? https://github.com/theforeman/foreman/pull/6253 is open to fix it.

**Comment by dammsd** [comment]
Thanks @ekohl

**Comment by ekohl** [comment]
Closing this in favor of the core PR.
