### ISSUE TITLE
JRUBY_JAR is obsolete in puppetserver 6

### ISSUE THREAD

**Issue by vchepkov** [theforeman/puppet-foreman#698]
FYI, parameter is obsolete:

```
# rpm -q puppetserver
puppetserver-6.0.2-1.el7.noarch

Dec  6 16:29:58 localhost puppetserver: Warning: the JRUBY_JAR setting is no longer needed and will be ignored.
```

**Comment by ekohl** [comment]
Perhaps you meant to file it at https://github.com/theforeman/puppet-puppet. Do note that if you correctly set the `$server_puppetserver_version` variable it should remove it automatically already.
