### ISSUE TITLE
Locations and Organizations get turned on by default in 11.0.0

### ISSUE THREAD

**Issue by jadestorm** [theforeman/puppet-foreman#711]
Hi folk, as of 11.0.0, if you leave them unconfigured in the module, the following two settings get removed from settings.yaml:
:locations_enabled: false
:organizations_enabled: false

This causes both to end up getting enabled which was quite a surprise.  =)

**Comment by ekohl** [comment]
It was a breaking change, but maybe should have been written clearly. For 1.21 they will always be turned on, but I also think we have a nice migration there. @tbrisker?

**Comment by jadestorm** [comment]
I see.  Having never had these turned on, if I simply enable them and then create one of each will it simply pull my existing stuff into the newly created org and location?

I think the thing that threw me for a loop is that this:
# $locations_enabled::            Enable locations? (Unused since 1.21)
#
# $organizations_enabled::        Enable organizations? (Unused since 1.21)

Reads to me as if the functionality itself is deprecated and gone as of 1.21.  Maybe instead of Unused since, might I suggest "Forced true starting with 1.21"?

**Comment by jadestorm** [comment]
huh.  that.. did not display the want I wanted.  ;)

**Comment by jadestorm** [comment]
There we go

**Comment by tbrisker** [comment]
This change is intentional, as these settings have been removed in 1.21. https://community.theforeman.org/t/proposal-remove-support-for-disabling-taxonomies-or-login/10972 contains further details, There was a UI notification about it in 1.20, and 1.21 will also contain a migration that will generate default organizations and locations and migrate all your resources to them.

**Comment by jadestorm** [comment]
Ah ok!  In that case I will simply wait for 1.21 since it will handle the heavy lifting for me.  =)  Thanks!

**Comment by ekohl** [comment]
Heads up as well that we removed the default value for authentication. In Foreman 1.20 and older the default is off. This does bring the risk that your instance will be unsecured.
