### ISSUE TITLE
puppetlabs-postgresql version compatibility

### ISSUE THREAD

**Issue by nadarashwin** [theforeman/puppet-foreman#721]
Hello team,

I was trying to go through the dependencies in order to install foreman on ubuntu18(bionic) machine.
This line says https://github.com/theforeman/puppet-foreman/blob/master/metadata.json#L29  use greater than or equal to 4.2.0 version of puppetlabs-postgresql

`      "name": "puppetlabs/postgresql",
      "version_requirement": ">= 4.2.0 < 6.0.0"
    },`

Now the problem is *4.2.0* has support for neither 16.04 nor 18.04. 
https://forge.puppet.com/puppetlabs/postgresql/changelog#560-2018-06-20 ... From 5.6 version the bionic support came in the picture.
We use Puppetfile which has cross dependencies and when  *https://github.com/theforeman/puppet-foreman* is linked in it, the *4.9.0* version of puppetlabs-postgresql is installed as we have pinned *mod 'puppetlabs/postgresql', '4.9.0'*.
If the minimum version requirement for 'puppetlabs/postgresql' is set from a point where the operating systems like 16.04 and 18.04 have support then it will be really helpful.

I may be wrong but wanted to make sure that I understand it properly.

**Comment by ekohl** [comment]
It has been pointed out a few times that we don't bump the lower bound that often. I've been keeping the API (which classes and which parameters) as the guide, but you're right that doesn't take operating systems into account nor compatibility with other module versions. We also typically test with the newest versions. Not sure what would be the best solution here.

**Comment by nadarashwin** [comment]
I personally found it a bit misleading while implementing due to the way Puppetfile play its part.
Changing the lower bound is something which has to be revisited :)

**Comment by mmoll** [comment]
Tbh, I don't think we should care for all the dependencies (and dependencies of dependencies) and their possible specific combinations. As long as the API is compatible the way we use it, the version specification is correct and everything else is only for bringing in "features".

**Comment by mmoll** [comment]
> We use Puppetfile which has cross dependencies and when https://github.com/theforeman/puppet-foreman is linked in it, the 4.9.0 version of puppetlabs-postgresql is installed as we have pinned mod 'puppetlabs/postgresql', '4.9.0'.

When using r10k (as opposed to librarian-puppet), situations like this occur frequently, but I don't see how this relates to the dependency specification of our module. It's the user's task with r10k to assemble the versions in the Puppetfile.

**Comment by ekohl** [comment]
I agree with @mmoll that it's on the user to make sure it works for their systems. 4.9.0 does support CentOS 7 so for some users that's a valid combination. There is no way to check operating systems within the tooling, but in general I prefer the latest versions. This is also what librarian-puppet does for you. There may be cases where the combinations no longer are installable due to shared dependencies (concat, stdlib) which means it may be a good reason to increase the minimum versions.

**Comment by nadarashwin** [comment]
Looks like the end user has to take care of it.
Thanks for the update @ekohl @mmoll .
