### ISSUE TITLE
userdata plugin was moved to core

### ISSUE THREAD

**Issue by timogoebel** [theforeman/puppet-foreman#739]
The `userdata` plugin was moved in core and will be part of Foreman 1.23.
Should we remove support for the plugin here or add a guard that does a noop on 1.23?

**Comment by ekohl** [comment]
We don't have a good way of detecting the version. I'd say we should add a note in the README about this. The installer does need a migration.

**Comment by ekohl** [comment]
Looks like this module was never exposed in the installer so that won't need any migration. It's probably good to add this in the upgrade warnings though.

**Comment by ekohl** [comment]
Added in https://github.com/theforeman/theforeman.org/pull/1425
