### ISSUE TITLE
db_username changes do not work

### ISSUE THREAD

**Issue by gcoxmoz** [theforeman/puppet-foreman#750]
I'm If I deploy foreman with the db_username parameter set to something besides the default 'foreman', the install goes sideways when the rake jobs try to connect to the DB:

```
Notice: /Stage[main]/Foreman::Database/Foreman_config_entry[db_pending_migration]/value: value changed '' to 'false'
Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: rake aborted!
Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: Sequel::DatabaseConnectionError: PG::ConnectionBad: FATAL:  Peer authentication failed for user "foreman_user"
```

Postgres' log says:
```
LOG:  provided user name (foreman_user) and authenticated user name (foreman) do not match
FATAL:  Peer authentication failed for user "foreman_user"
```

Taking out my db_username parameter or setting it to 'foreman' leads to a clean install.  I'm no DBA but it looks like this is a missing postgresql::server::pg_hba_rule rule to allow for the OS username != database username.

**Comment by ekohl** [comment]
I think that's correct for the puppetlabs-postgresql defaults, but this module doesn't manage the postgresql server rules. That's out of scope and something you need to do at a profile layer. The primary use case of the parameter is for remote databases.
