### ISSUE TITLE
foreman::puppetmaster does not edit puppet.conf

### ISSUE THREAD

**Issue by gcoxmoz** [theforeman/puppet-foreman#757]
When foreman::puppetmaster::reports is true, https://github.com/theforeman/puppet-foreman/blob/12.2.0/manifests/puppetmaster.pp#L38-L51 puts out scripts, but leaves it up to manual intervention to place 'foreman' in the puppet.conf reports field.

Compare to https://github.com/puppetlabs/puppetlabs-puppetdb/blob/7.4.0/manifests/master/config.pp#L132-L147 and https://github.com/puppetlabs/puppetlabs-puppetdb/blob/7.4.0/manifests/master/report_processor.pp#L20-L27 - when reports are enabled with this module, it edits itself completely into service.

The actual change here is not very large.  However, cloning this code would be the first use of the inifile module (introducing a new dependency to this module), and since this module has existed so long without such a hook, I'm wondering if "don't get into editing puppet.conf" has been a deliberate choice.  So I'm opening this as an issue first to see if this is something that is "my problem" or if I should pursue a PR for.

**Comment by ekohl** [comment]
This is indeed a deliberate choice. What puppetlabs-puppetdb does is IMHO very annoying and conflicts with how we manage Puppet in our module (https://github.com/theforeman/puppet-puppet/).

**Comment by gcoxmoz** [comment]
That's understandable (and makes me really glad I asked before PR'ing).  May I then suggest a comment in config.pp in the 'if reports' block, pointing to docs/reminding folks of the need to manage the reports line, so it's clear that this module doesn't + won't do that?

**Comment by ekohl** [comment]
Comments pointing users to docs are fine and I'll gladly merge such a thing. The puppetmaster class doc would also be a good place IMHO, even though currently we don't have puppet-strings docs there and don't generate a `REFERENCE.md`. Both is probably good.
