### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by jby** [theforeman/puppet-foreman#771]
In the manual (here: https://theforeman.org/manuals/1.3/index.html#3.5.4PuppetReports) is a reference to foreman-report_v2.rb.erb which doesn't seem to exist any more in this repo.

Anyone care to update the docs to the current procedure and files?

**Comment by ekohl** [comment]
You are looking at the 1.3 version of the docs which is ancient. More recent versions should link to https://github.com/theforeman/puppet-foreman/blob/master/files/foreman-report_v2.rb.
