### ISSUE TITLE
AD registration with GSS proxy fails

### ISSUE THREAD

**Issue by kuwv** [theforeman/puppet-foreman#796]
Installer fails to register satellite to AD due to bad default while querying sssd_services. This working in 6.4 and fails in 6.5 and 6.6. Here are the procedures:

https://access.redhat.com/documentation/en-us/red_hat_satellite/6.5/html/administering_red_hat_satellite/chap-red_hat_satellite-administering_red_hat_satellite-configuring_external_authentication#sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Configuring_External_Authentication-Using_Active_Directory

```
Evaluation Error: Operator '[]' is not applicable to an Undef Value. (file: /usr/share/foreman-installer/modules/fore
man/manifests/config.pp, line: 136, column: 43) on node
```

**Comment by kuwv** [comment]
Current versions are:
```
$ puppet --version
5.5.12
$ facter --version
3.11.8 (commit eb5f71136af5012f3a7169ed3a77a111c1e4d765)
```

Seems the facts might not be populating correctly due to: https://puppet.com/docs/puppet/6.10/custom_facts.html#concept-243

```
Note: Facter 3.0 removed the Ruby implementations of some features and replaced them with a custom facts API. Any custom fact that requires one of the Ruby files previously stored in lib/facter/util fails with an error.
```

**Comment by kuwv** [comment]
Guess this isn't monitored. :(

**Comment by ekohl** [comment]
I wonder if b0f88ed52539ca74cf58017d97bbb8327b083e1f is the cause of this. However, it should not fail with that error since it does check if the facts exist. I'm currently looking at writing some tests.

**Comment by ekohl** [comment]
I spent some time on adding tests and could only get them to work with string keys in https://github.com/theforeman/puppet-foreman/pull/801. Would you mind testing if this is also a solution to your problem?

**Comment by kuwv** [comment]
@ekohl My apologies, I hadn't seen that you commented. I will give it a check sometime this week.

**Comment by ekohl** [comment]
Do you by any chance have the `ipa` module installed? That also provides the `ipa` fact and the conflict is an issue. I'll rename the fact in this module to `foreman_ipa` to avoid the naming issue.
