### ISSUE TITLE
add ldap params for the settings.yaml.erb

### ISSUE THREAD

**Issue by florent26** [theforeman/puppet-foreman#819]
Hi,
Is it possible to add a params for enable ldap from the /etc/foreman/settings.yaml ?

For example :
`# LDAP`
`:ldap:`
`  :enabled: true`

Currently the module doesn't allow it.

Thanks,

**Comment by ekohl** [comment]
As you correctly observed, this is currently not possible. I personally haven't used LDAP but https://theforeman.org/manuals/1.24/index.html#4.1.1LDAPAuthentication suggests it's not really a setting but rather an external auth source. We currently don't support managing those. It'd be closer to [the foreman_smartproxy type](https://github.com/theforeman/puppet-foreman/blob/master/lib/puppet/type/foreman_smartproxy.rb). There are some modules that have all data types but currently I can't find them. In the past there was https://github.com/theforeman/puppet-foreman/pull/579

**Comment by florent26** [comment]
Hi,
Thanks for your response.

But it's strange because currently I have a Foreman production instance with ldap and that is not managed by the Foreman Puppet module. And I'm testing the Foreman Puppet module on a test instance and if I don't add this in the settings.yaml I can't see the "ldap authentication" menu in "Administer" in the Foreman IHM.

Is it not possible to just add a Boolean params "enable_ldap" with a default value to "false" ?

Thanks.

**Comment by ekohl** [comment]
No, because Foreman doesn't actually have such a config setting. This module only reflects what [Foreman](https://github.com/theforeman/foreman) actually supports.

**Comment by fe80** [comment]
Hello,

We can change the settings management with concat for add personal patch eventually ?

I can create a MR if you want

Regards,

**Comment by ekohl** [comment]
I don't think such a setting even works. However, it already is a concat so it should be rather trivial to test it out for yourself if you want:
https://github.com/theforeman/puppet-foreman/blob/d33e10c2d157c392b1289215cb192b00d2e30c98/manifests/config.pp#L22-L32

**Comment by fe80** [comment]
Yes sorry I doesn't read correctly the code xD

Ty :)
