### ISSUE TITLE
Please add db_type back.

### ISSUE THREAD

**Issue by anesterova** [theforeman/puppet-foreman#861]
We are using mysql as a DB, not postgres, that's why the latest module version just breaks our puppet/foreman setup.
Please add it at least in the database.yaml.erb, so we could use it.

**Comment by ehelms** [comment]
As of Foreman 2.0, mysql support was dropped and only PostgreSQL is supported. This started with the 14.0 version of the puppet module to match expectations (https://github.com/theforeman/puppet-foreman/pull/781)
