### ISSUE TITLE
default puppetmaster is highly unusual

### ISSUE THREAD

**Issue by anarcat** [theforeman/puppet-foreman#864]
I was surprised to find that this module configures nodes to connect to themselves by default. For example, this configuration:

```
include puppet
```

will (correctly) configure a puppet agent to run on the given node, but will (incorrectly, IMHO) tell it to connect to `$fqdn`. In my case, this yields the error:

```
Error: Could not request certificate: Failed to open TCP connection to curie.anarc.at:8140 (Connection refused - connect(2) for "curie.anarc.at" port 8140)
```

`curie.anarc.at` is my workstation here. it should instead try to connect to `puppet` or `puppet.$DOMAIN` which is `puppet.anarc.at` in my case.

this change from standard breaks over a decade of convention in the puppet discovery process. i find it quite surprising and can't think of a reason for it.

i believe it should be changed to just *nothing*: no `server` line should be added to `puppet.conf` unless provided by the user, in which case the upstream `puppet agent` defaults will apply (as they should).

**Comment by ekohl** [comment]
Did you intend to file this against [puppet-puppet](https://github.com/theforeman/puppet-puppet/)?

**Comment by anarcat** [comment]
i did, sorry!
