### ISSUE TITLE
foreman-report_v2 disappeared from master branch ?

### ISSUE THREAD

**Issue by JoeriBouchet** [theforeman/puppet-foreman#939]
The documentation is broken. https://www.theforeman.org/manuals/2.4/index.html
It points at paragraph 3.5.4 to the foreman-report_v2 file on https://raw.githubusercontent.com/theforeman/puppet-foreman/master/files/foreman-report_v2.rb

However this is a dead link. Older documentations have the same link.
When searching for the file I can ONLY find it on older branches, but for some reason it has disappeared on the master branch? 

There may be a good reason for that, but if so , it needs to be documented and documentation updated.

**Comment by ekohl** [comment]
Yes, this was indeed still on my TODO list. It has moved to its own module and is now found as https://github.com/theforeman/puppet-puppetserver_foreman/blob/master/files/report.rb. Similarly, https://github.com/theforeman/puppet-puppetserver_foreman/blob/master/files/enc.rb is the former node.rb script.

**Comment by ekohl** [comment]
In https://github.com/theforeman/theforeman.org/commit/b8e8ad0b4b2772b8d329c1cfe755994140abca81 the documentation was updated to reflect this.
