### ISSUE TITLE
Customisable Yum repository base URL

### ISSUE THREAD

**Issue by nbarrientos** [theforeman/puppet-foreman#942]
We've got our own mirror of the Foreman Yum repositories so it'd be nice if the module allowed to set the base URL of the Yum repository which is currently hard-coded to `https://yum.theforeman.org/`:

https://github.com/theforeman/puppet-foreman/blob/master/manifests/repos/yum.pp#L18

As a bonus it'd be nice as well if the path to the GPG public key could be customised as well to accommodate different repository mirroring approaches.

We have a local patch with a proposed fix that we'd have to improve before submitting but I don't know if I'll have to time to work on in the near future so if somebody wants to provide one just go ahead :)

**Comment by ekohl** [comment]
Hardcoded strings are almost always bad. I'd be fine with more parameters
