### ISSUE TITLE
Any plans to migrate from camptocamp-systemd to puppet-systemd ?

### ISSUE THREAD

**Issue by damonmaria** [theforeman/puppet-foreman#982]
I tried to convert my control repo to `puppet-systemd` but `theforeman-foreman` referencing `camptocamp-systemd` holds me back from doing so.

AFAICT the puppet module is backwards compatible with the camptocamp one and I presume will get better support going forward.

**Comment by ekohl** [comment]
This is indeed something we should do, but we're in the middle of branching Foreman 3.0 so it'll have to wait to be merged until we have. I'd appreciate PRs to do so (including making sure the transitive dependencies are also correct). Hopefully in a few days we can start merging bigger changes again.

**Comment by evgeni** [comment]
This happened in 19.0.0 (via https://github.com/theforeman/puppet-foreman/commit/857ddefc7f42ad63648aa9f13298a92a83df3719), closing.
