### ISSUE TITLE
foreman_config_entry consuming polluted value

### ISSUE THREAD

**Issue by nbarrientos** [theforeman/puppet-foreman#989]
`foreman_config_entry` [consumes](https://github.com/theforeman/puppet-foreman/blob/master/lib/puppet/provider/foreman_config_entry/cli.rb#L55) the whole string printed to stdout by `foreman-rake -- config -k foo` when invoked.

If the apipie cache is not generated, Foreman [prints to stdout](https://github.com/theforeman/foreman/blob/develop/config/initializers/apipie.rb#L92) some text, example:

```
# foreman-rake -- config -k rss_enable
API controllers newer than Apipie cache! Run apipie:cache rake task to regenerate cache.
false
```
So, as the requested value via `foreman_config_entry` does not match the current value, (it does actually, but it's prefixed by the apipie bit) then the setting is incorrectly re-set (making the Puppet run slower and adding rubbish to the audit log, for instance).

```
puppet-agent[348248]: (/Stage[main]/.../Foreman_config_entry[create_new_host_when_report_is_uploaded]/value) value changed "API controllers newer than Apipie cache! Run apipie:cache rake task to regenerate cache.\nfalse" to 'false' (corrective)
```

We have this patch locally:

```diff
code/lib/puppet/provider/foreman_config_entry/cli.rb | 1 +

modified   code/lib/puppet/provider/foreman_config_entry/cli.rb
@@ -17,6 +17,7 @@ Puppet::Type.type(:foreman_config_entry).provide(:cli) do
           :gid                => 'foreman' }.merge(options)
       )
       status = $?
+      output.slice! "API controllers newer than Apipie cache! Run apipie:cache rake task to regenerate cache.\n"
       output if status.success?
     end
   end
```
To prevent this from happening but of course it's not the best solution. Ideally the output produced by Foreman should go to `stderr` instead.

What do you think?

**Comment by ekohl** [comment]
> To prevent this from happening but of course it's not the best solution. Ideally the output produced by Foreman should go to `stderr` instead.

Agreed. That particular line is here:
https://github.com/theforeman/foreman/blob/e2918f95f2c11bef3a287f63949387d47c771202/config/initializers/apipie.rb#L92

I'd happily support a patch that fixes it.

**Comment by nbarrientos** [comment]
Thanks. So just to confirm the next steps would be to close this issue, create one in the Foreman bug tracker and eventually send a patch for it, right?

**Comment by ekohl** [comment]
Yes, I think so. I'd also add a link to the Foreman Redmine issue here and refer to this issue in the Redmine issue just to keep it connected, but it wouldn't surprise me if you'd already do that anyway :)

**Comment by nbarrientos** [comment]
As discussed: https://projects.theforeman.org/issues/33369
