### ISSUE TITLE
Ensuring the ruby module stream on rhel 8

### ISSUE THREAD

**Issue by pkranenburg** [theforeman/puppet-foreman#990]
cf.  revision 2a9f9ed482c299749b467a92f248407c3010c9e0
The package resource should read:

   package { 'ruby':
       ensure          => '2.7',
       enable_only => true,
       provider        => 'dnfmodule',
   }

in its current form, it will switch to the desired '2.7' stream, but subsequent puppet runs do not properly recognise the active stream.

**Comment by ekohl** [comment]
I've noticed a similar thing. It may be due to `enable_only`. However, I've heard of some idempotency issues if you leave it out.

**Comment by pkranenburg** [comment]
I think 'enable_only' should not be left out. If you don't have it, the dnfmodule provider will also install all packages in the default dnf stream profile, in addition to enabling the stream. The form:

package { 'ruby':
  ensure => '2.7',
  enable_only => true,
  provider => 'dnfmodule',
}

works fine.

Note: recent ::postgresql modules also feature 'appstream' support and use 'ensure => $version' to get it done.

**Comment by erik-frontify** [comment]
I do have the same issue.
Notice: /Stage[main]/Foreman::Repo/Package[ruby:2.7]/ensure: created (corrective)
And in fact looking it up shows:
```
puppet resource package 'ruby:2.7' provider=dnfmodule
Notice: /Package[ruby:2.7]/ensure: created
package { 'ruby:2.7':
  ensure   => 'purged',
  provider => 'dnfmodule',
}
```
But this would look good:
```
puppet resource package 'ruby' provider=dnfmodule
package { 'ruby':
  ensure   => '2.7',
  provider => 'dnfmodule',
}
```

**Comment by bastelfreak** [comment]
I think I've a similar issue. I see the following on each puppet run:
```
Debug: Prefetching dnfmodule resources for package
Debug: Executing: '/usr/bin/dnf --version'
Debug: Executing: '/usr/bin/dnf module list -d 0 -e 1'
Debug: Executing: '/usr/bin/dnf module list -d 0 -e 1'
Debug: Executing: '/usr/bin/dnf module enable -d 0 -e 1 -y ruby:2.7'
Notice: /Stage[main]/Foreman::Repo/Package[ruby:2.7]/ensure: created
```

It's a CentOS 8 box:
```
# puppet facts os
{
  "os": {
    "architecture": "x86_64",
    "distro": {
      "description": "CentOS Linux release 8.5.2111",
      "id": "CentOS",
      "release": {
        "full": "8.5.2111",
        "major": "8",
        "minor": "5"
      }
    },
    "family": "RedHat",
    "hardware": "x86_64",
    "name": "CentOS",
    "release": {
      "full": "8.5.2111",
      "major": "8",
      "minor": "5"
    },
    "selinux": {
      "config_mode": "enforcing",
      "config_policy": "targeted",
      "current_mode": "enforcing",
      "enabled": true,
      "enforced": true,
      "policy_version": "33"
    }
  }
}
```

and I call the module like this:

```
  class { 'foreman':
    logging_type             => 'journald',
    initial_admin_username   => 'bastelfreak',
    initial_admin_first_name => '*',
    initial_admin_last_name  => '*',
    initial_admin_email      => '*',
    register_in_foreman      => true,
    rails_cache_store        => {
      'type'    => 'redis',
      'urls'    => ['localhost:6379/0'],
      'options' => {
        'compress'  => 'true',
        'namespace' => 'foreman',
      },
    },
  }
```

The installed package:

```
root@puppet ~ # puppet resource package 'ruby:2.7'
package { 'ruby:2.7':
  ensure   => 'purged',
  provider => 'dnf',
}
root@puppet ~ # puppet resource package ruby
package { 'ruby':
  ensure   => '2.7.4-137.module_el8.4.0+875+807aec38',
  provider => 'dnf',
}
root@puppet ~ #
```

**Comment by ekohl** [comment]
We're looking into https://projects.theforeman.org/issues/34126. It doesn't describe much, but that would be a more native solution that DNF would understand.

**Comment by pkranenburg** [comment]
I'm not sure what this feature will entail exactly, but it doesn't sound like something that's just a trivial patch to the packaging system.

Meanwhile, this bug in the foreman puppet module is extremely easy to fix: in **foreman::repo** just replace the faulty fragment

     package { 'ruby:2.7':
        ensure      => installed,
        enable_only => true,
        provider    => 'dnfmodule',
    }

with

  **package { 'ruby':
    ensure => '2.7',
    enable_only => true,
    provider => 'dnfmodule',
 }**

**Comment by ekohl** [comment]
Could you submit that as a PR?

**Comment by pkranenburg** [comment]
Done, See  PR#1012

**Comment by ekohl** [comment]
Thanks. I ended up merging https://github.com/theforeman/puppet-foreman/pull/1015.
